### ISSUE TITLE
Qt/QML support

### ISSUE THREAD

**Issue by EbonJaeger** [zed-industries/extensions#1045]
### Check for existing issues

- [X] Completed

### Language

QML

### Tree Sitter parser link

https://github.com/yuja/tree-sitter-qmljs

### Language server link

https://github.com/qt/qtdeclarative/tree/dev/tools/qmlls

### Misc notes

Modern Qt applications are usually a mixture of C++ and QML. C++ is already pretty well-supported in Zed, at least from what I can tell, but there is no support for QML. Having this support for Zed would be great for Linux and cross-platform developers.

**Comment by a-andreyev** [comment]
related: https://github.com/zed-industries/extensions/pull/998

**Comment by EbonJaeger** [comment]
Ah, I looked for open issues, but I did not look for open Pull Requests xD

**Comment by lkroll** [comment]
I made an extension that adds syntax highlighting for QML: https://github.com/lkroll/zed-qml
I may add language server support for qmlls in the future, but haven't figured that out yet.

**Comment by JosephTLyons** [comment]
Since an [QML extension](https://github.com/lkroll/zed-qml) technically does exist now, I'm going to close this issue out.

<img width="718" alt="SCR-20240716-miii" src="https://github.com/user-attachments/assets/9c52d5f1-baff-4f40-bfb3-2338a6c0deeb">
