### ISSUE TITLE
D

### ISSUE THREAD

**Issue by aberba** [zed-industries/extensions#1048]
### Check for existing issues

- [X] Completed

### Language

D

### Tree Sitter parser link

https://github.com/gdamore/tree-sitter-d

### Language server link

https://github.com/Pure-D/serve-d

### Misc notes

D language (Dlang) has a VS Code extension which can be useful as a reference: https://github.com/Pure-D/code-d

**Comment by aberba** [comment]
I was told there is already an initial support for D merged but it seems LSP support isn't yet available https://github.com/zed-industries/extensions/pull/606

**Comment by cyrusmsk** [comment]
Also https://github.com/zed-industries/extensions/issues/204

**Comment by aberba** [comment]
There's a D extension already created here https://github.com/staysail/zed-d. A good candidate for official inclusion in the extension repository/store.

**Comment by maxdeviant** [comment]
The D extension is already available on the extension page (although it can be a bit hard to search for, at the moment).

AFAICT the published version already has language server support.

**Comment by aberba** [comment]
@maxdeviant also the menu to open extensions is not the best design where it is placed. Why are they placed under an arrow icon?
