### ISSUE TITLE
Kanagawa

### ISSUE THREAD

**Issue by ryoppippi** [zed-industries/extensions#105]
### Check for existing issues

- [X] Completed

### Misc notes

https://github.com/rebelot/kanagawa.nvim

**Comment by JosephTLyons** [comment]
A [Kanagawa theme extension](https://github.com/ethangilmore/zed-kanagawa) now exists.

<img width="716" alt="SCR-20240716-mkhj" src="https://github.com/user-attachments/assets/4385970d-7acd-41f9-83f5-1ad8cd493d7c">
