### ISSUE TITLE
I Would love to Start  building extensions for Zed

### ISSUE THREAD

**Issue by yhoungdev** [zed-industries/extensions#1065]
### Check for existing issues

- [X] Completed

### Misc notes

I would like to start  developing extensions for the Zed editor. With my experience in building VS Code extensions, I am keen to leverage and expand my skills by contributing to the Zed ecosystem.

 I would appreciate any resource(s) that points to building extensions for Zed

**Comment by JosephTLyons** [comment]
Hey @yhoungdev - here is some documentation for building extensions:

- https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md

Extensions can also provide custom snippets and tasks, but these things are likely not considered "stable" yet and might change.

**Comment by yhoungdev** [comment]
Ok that is awesome
