### ISSUE TITLE
Bazel support

### ISSUE THREAD

**Issue by romannikov** [zed-industries/extensions#1098]
### Check for existing issues

- [X] Completed

**Comment by p00f** [comment]
There's a starlark extension: https://github.com/zaucy/zed-starlark/

**Comment by romannikov** [comment]
I searched for it, but missed, sorry

**Comment by anonrig** [comment]
I think this should be reopened. Starlark extension doesn't mean Bazel build support

**Comment by ofek** [comment]
@MrSubidubi Can this be reopened? There is no support for the Bazel build system itself.
