### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by Neogamezzz** [zed-industries/extensions#1111]
### Check for existing issues

- [X] Completed

### Language

C#

### Tree Sitter parser link

https://github.com/tree-sitter/tree-sitter-c-sharp

### Language server link

https://github.com/razzmatazz/csharp-language-server

### Misc notes

I would like to have C# language support and Blazor

**Comment by maxdeviant** [comment]
There is already a C# extension available: https://github.com/zed-industries/zed/tree/1ea363b0200d3d796f38dc6ea75ac3deb188d102/extensions/csharp
