### ISSUE TITLE
<name_of_language> hola soy crass hablo español

### ISSUE THREAD

**Issue by Crass-Nua** [zed-industries/extensions#1112]
### Check for existing issues

- [X] Completed

### Language

español

### Misc notes

hola saludos 
soy crass  gracias por brindarnos estas oportunidad, herramientas increíbles que nos brindan solicito un petición en español, las manualidades los funciones. 
gracioas un gran exito.

**Comment by maxdeviant** [comment]
Hey @Crass-Nua, what is it exactly you're asking for here?
