### ISSUE TITLE
HLSL syntax highlighting

### ISSUE THREAD

**Issue by XavierCS-dev** [zed-industries/extensions#1121]
### Check for existing issues

- [X] Completed

### Describe the feature

I was wondering whether it would be possible to get syntax highlighting for HLSL in Zed? Would be really useful.

**Comment by XavierCS-dev** [comment]
Doesn't seem too hard to do this myself...

**Comment by maxdeviant** [comment]
There is an HLSL extension now: https://github.com/zed-industries/extensions/pull/1276

**Comment by XavierCS-dev** [comment]
> There is an HLSL extension now: #1276

Ah thanks for letting me know :)
