### ISSUE TITLE
RBS - type signatures for Ruby

### ISSUE THREAD

**Issue by reesericci** [zed-industries/extensions#1196]
### Check for existing issues

- [X] Completed

### Language

RBS

### Tree Sitter parser link

N/A

### Language server link

N/A

### Misc notes

RBS is the new type signature specification in Ruby 3 for use by type checkers.

https://github.com/ruby/rbs

https://github.com/soutaro/steep uses RBS

**Comment by vitallium** [comment]
I created a WIP pull request that adds support for RBS files https://github.com/zed-industries/zed/pull/15778

**Comment by reesericci** [comment]
Resolved by merged PR #15778
