### ISSUE TITLE
The same code compiled on Zed & RustRover gives different results

### ISSUE THREAD

**Issue by wooowchik** [zed-industries/extensions#1214]
### Check for existing issues

- [X] Completed

### Misc notes

![Screenshot from 2024-08-07 04-47-22](https://github.com/user-attachments/assets/bb6341dc-46a9-473c-a860-1dbc04defb19)
Why this code:
```
fn interproduct(a: i32, b: i32, c: i32) -> i32 {
    return a * b + b * c + c * a;
}
fn main() {
    println!("result: {}", interproduct(120, 100, 248));
}

```
on Zed gives me: Hello, world!
but on JetBrains RustRover gives me the correct result which is: result: 66560 
???

**Comment by wooowchik** [comment]
Last but not less important thing!!!

Zed is actually not obeying the color scheme of any theme which I apply on it...
Absolutely any color theme which I Apply is always in some way distorted/altered, basically is like the editor use to pick it's own color by ignoring the original applied theme.

**Comment by osiewicz** [comment]
Hi, thanks for filling out this issue.
1. You have not saved your file in Zed, which is probably why `cargo run` did not pick up your changes.
2. Neither the Rust part of your issue nor scheming issue is related to this repository per se; please file an issue on the [main issue tracker](https://github.com/zed-industries/zed/issues) if you think that there's a bug in how we handle color schemes from extensions.

I'll go ahead and close this issue.
