### ISSUE TITLE
Testing local language extension fails

### ISSUE THREAD

**Issue by piechologist** [zed-industries/extensions#124]
I put together a local extension that consists of the following files:
```
drwxr-xr-x     - '~/Library/Application Support/Zed/extensions/installed'
drwxr-xr-x@    - ├── fish
drwxr-xr-x@    - │  ├── grammars
.rwxr-xr-x@  75k │  │  └── fish.wasm
drwxr-xr-x@    - │  ├── languages
drwxr-xr-x@    - │  │  └── fish
.rw-r--r--   379 │  │     ├── config.toml
.rw-r--r--   939 │  │     └── highlights.scm
.rw-r--r--   315 │  └── extension.json
```

Running `zed: reload extensions` results in an error message in the log:
```
2024-02-25T11:20:31+01:00 [ERROR] crates/extension/src/extension_store.rs:573: failed to load extension.json

Caused by:
    Not a directory (os error 20)
```

I can see `Fish` in the list of languages but opening a fish script and switching the language has no effect.

My file structure and contents match other (published) extensions such as `LOG` or `R`. I read about some issues with local extensions but I'm not sure if the've been resolved. 

Any help how to debug this would be appreciated. My files are in [this repo](https://github.com/piechologist/zed-fish); for local testing I swapped fish.toml from the repo to fish.wasm as described in [AUTHORING_EXTENSIONS.md](https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md).

EDIT:

I tried Zed Preview 0.124.4 and the error message is gone. Now I can't reproduce it in Zed stable 0.123.6 anymore. The extension still doesn't work.

**Comment by zarifpour** [comment]
Having the same issue here, but I did not try reloading extensions:

https://github.com/zed-industries/extensions/issues/121#issuecomment-1962858461

**Comment by piechologist** [comment]
Closing this issue, fish has been implemented with #274.

**Comment by Moshyfawn** [comment]
I was under the impression that this issue was primarily about local expansion testing, which I don't think has been resolved yet.

**Comment by piechologist** [comment]
@Moshyfawn You're right. I just installed the fish extension #274 and could make some local changes that work. 

In hindsight, I guess I made some mistake when trying to build an extension from scratch that seems irrelevant now. That's why I closed this issue.

**Comment by Moshyfawn** [comment]
Fair enough!

Any pointers as to what you found caused the problems when you tested the extension locally?

**Comment by piechologist** [comment]
> Any pointers as to what you found caused the problems when you tested the extension locally?

I assume it was my fish.wasm as this was the only thing I couldn't double-check. The other files are just plain text...

`tree-sitter-macos-x64 build-wasm` finished in seconds but it's really a black box for me. I was thinking about a macOS notarization problem as the *.wasm files have the executable bit set but the extensions work without that bit set. There have been two updates to Zed stable since I tried (fixing at least the `Not a directory (os error 20)` issue) so I guess it's time to move on.

After several years of grumpily using VSCode/VSCodium I can't wait to migrate to Zed. The fish extension is here now and is evolving, LSP for extensions and Julia support will arrive soon enough 🎉.

Thank you for following up!
