### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by ShawSumma** [zed-industries/extensions#135]
**Is your feature request related to a problem? Please describe.**
I do not have syntax highlighting on makefiles, this makes typos and other issues easy to miss.

**Describe the solution you'd like**
Makefile highlighting support

**Describe alternatives you've considered**
For now the alternative is to go without highlighting 

**Additional context**
Makefiles are essential to a large number of C projects, having syntax highlighting support would make dealing with their quirks much better.

**Comment by drornir** [comment]
The `make` extension has been fixed! https://github.com/caius/zed-make/releases/tag/v1.0.0
I think this issue can be closed

**Comment by ShawSumma** [comment]
That sounds reasonable.

I'll close it now, feel free to reopen if need be.
