### ISSUE TITLE
Scala

### ISSUE THREAD

**Issue by mhzajac** [zed-industries/extensions#136]
It would be nice to support Scala language syntax. [Metals](https://scalameta.org/metals/) is a Scala language server that is currently well-maintained.

**Comment by alexthe2** [comment]
given the pr is merged, is there a time update?

**Comment by WeetHet** [comment]
> given the pr is merged, is there a time update?

Right now the work is being done to allow this to be an extension (see crates/extension_ui in the main repo)

**Comment by SouchonTheo** [comment]
Hello everyone 👋,
Is there any update about the topic ? Really excited to test zed !

**Comment by dabrowski-adam** [comment]
The Scala extension has been published and can be download from within Zed:

> ![image](https://private-user-images.githubusercontent.com/601206/317819817-721130fc-b3ab-499a-b621-22fdfe4983d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODkzNjEsIm5iZiI6MTcxMzE4OTA2MSwicGF0aCI6Ii82MDEyMDYvMzE3ODE5ODE3LTcyMTEzMGZjLWIzYWItNDk5YS1iNjIxLTIyZmRmZTQ5ODNkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMzUxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2UzZjQwNTIwMjJjMjc1MjA5MDQ3Y2M1ODAxZDc3NWIyNzZhMzEwODgxZGFlN2RiNTMyMTdiZWFjMzYxYzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MjoKKrJRgOYoSSTrUw7VZGjqoWGjuFtWTNJPVZeY3pg)

https://github.com/zed-industries/zed/pull/7933#issuecomment-2025730788

You can find the code under the [scalameta/metals-zed](https://github.com/scalameta/metals-zed) repo.

**Comment by maxdeviant** [comment]
Closing this out, as we now have a Scala extension.
