### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by undersquire** [zed-industries/extensions#138]
There is the [kotlin-language-server](https://github.com/fwcd/kotlin-language-server) that could be used.

**Comment by henrik242** [comment]
👀  https://github.com/evrsen/zed-kotlin/issues/1

**Comment by eth0net** [comment]
I'm working on Docker Compose support rn but happy to fork Kotlin and pick this one up after ^^

**Comment by maxdeviant** [comment]
Closing this out, as there is now a Kotlin extension available: https://github.com/zed-extensions/kotlin

If there are improvements you'd like to see for Kotlin, please open an issue or PR on that repo.

**Comment by FalconSlayer51** [comment]
Hello guys this is just let you know that the current kotlin extension does nothing. How do we configure it , its not working out of the box like other extensions.

**Comment by FalconSlayer51** [comment]
> Closing this out, as there is now a Kotlin extension available: https://github.com/zed-extensions/kotlin
> 
> If there are improvements you'd like to see for Kotlin, please open an issue or PR on that repo.

This version of extension is not working on windows, i ve fixed that issue but kotlin extension contributors are no longer active! What should i do @maxdeviant @JosephTLyons

**Comment by maxdeviant** [comment]
> > Closing this out, as there is now a Kotlin extension available: https://github.com/zed-extensions/kotlin
> > If there are improvements you'd like to see for Kotlin, please open an issue or PR on that repo.
> 
> This version of extension is not working on windows, i ve fixed that issue but kotlin extension contributors are no longer active! What should i do @maxdeviant @JosephTLyons

v0.1.0 of the Kotlin has just been released with a number of improvements.

It should be available to download in the next few minutes.
