### ISSUE TITLE
CrystalTheme

### ISSUE THREAD

**Issue by v1mkss** [zed-industries/extensions#1382]
### Check for existing issues

- [X] Completed

### Misc notes

theme url: https://gitlab.com/crystalnetwork-studio/themes/zed-editor
If necessary, I can upload it to github

**Comment by blaqat** [comment]
Is this a theme request? Or a complete theme you wish to merge. If the latter you just need to open a PR following the instructions here: https://zed.dev/docs/extensions/developing-extensions#publishing-your-extension

**Comment by v1mkss** [comment]
> Is this a theme request? Or a complete theme you wish to merge. If the latter you just need to open a PR following the instructions here: https://zed.dev/docs/extensions/developing-extensions#publishing-your-extension

Oh, I didn't finish reading.
