### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by aleksrutins** [zed-industries/extensions#139]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use Zed to work on my Swift projects.

**Describe the solution you'd like**
[SourceKit-LSP](https://github.com/apple/sourcekit-lsp) could be used.

**Describe alternatives you've considered**
N/A?

**Screenshots**
N/A

**Comment by yeahitsjan** [comment]
Is there any update on this? I would really like to move from Sublime Text to Zed. Atleast highlighting would be nice..

**Comment by marcusziade** [comment]
> Is there any update on this? I would really like to move from Sublime Text to Zed. Atleast highlighting would be nice.. 

There's a syntax extension. Haven't tried it yet.

**Comment by Moshyfawn** [comment]
> Is there any update on this? I would really like to move from Sublime Text to Zed. Atleast highlighting would be nice.. 

There's already a community Swift syntax highlighting [extension](https://github.com/samuser107/zed-swift-extension). Try searching for it in the extensions tab in Zed.

The ability to tie in an LSP is coming to See a bit later.

**Comment by Shock9616** [comment]
> I'm using sourcekit-lsp in Neovim as well and see no slowdowns.

I also use Neovim, the lsp isn't the thing causing slowdowns, it's 100% the treesitter grammar. All the slowdowns go away as soon as I disable treesitter

**Comment by awamser** [comment]
The workaround, until LSP is added, is to install Apple's swift-format ( https://github.com/apple/swift-format ) and run it from the command line.

Example
`find ./Sources -name "*.swift" -exec swift-format -i {} \;`

**Comment by JosephTLyons** [comment]
As others have mentioned, the extension store now has an extension for Swift:

<img width="1476" alt="SCR-20240412-lnuu" src="https://github.com/zed-industries/extensions/assets/19867440/fe8fb22c-eeae-4dbc-9752-dbb4875c33a0">

Zed extensions now support language servers, but it looks like the package hasn't been updated yet to include one.  Here is [the issue](https://github.com/louisnicolas-longheval-vinci/zed-swift-extension) requesting that.

Let's close this issue out and move dialogue / PRs over the extension owner's (@louisnicolas-longheval-vinci) repository.

**Comment by awamser** [comment]
Based on the author's comments for the zed-swift extension, there are plans to add something other than source-kit support.


https://github.com/louisnicolas-longheval-vinci/zed-swift-extension/issues/5

**Comment by furby-tm** [comment]
I'm a bit confused on the approach here ~ What was the reason for giving Swift the boot, and ejecting it out of Zed, while keeping the other 44 languages that Zed ships with out of the box?

**Comment by deevus** [comment]
> I'm a bit confused on the approach here ~ What was the reason for giving Swift the boot, and ejecting it out of Zed, while keeping the other 44 languages that Zed ships with out of the box?

It looks like languages as extensions is the preferred approach going forward. Check out the breaking changes here: https://zed.dev/releases/stable/0.130.4

**Comment by furby-tm** [comment]
Preferred, as in _rendered useless_ by removing the ability to add a _sourcekit adapter_ for full and proper support?

Like [**so**](https://github.com/wabiverse/zed/commit/d180aa511da326e1193536a5246f233c6954b03d#diff-d29f6dd9e43c17ea0d810c5ab6c24009716901a9b871934bf95f525d1e43dd33R321)?

**Comment by JosephTLyons** [comment]
My current understanding is that all of the languages currently baked into Zed, will be pulled out into extensions. Those removals are happening in batches, so the process isn't finished.

> Preferred, as in rendered useless by removing the ability to add a sourcekit adapter for full and proper support?

Unless there's some edge case that specifically prevents `sourcekit` from being used as a language server in Zed, extensions now have the ability to install language servers on the user's system.

**Comment by furby-tm** [comment]
@joshrutkowski I will give this a shot for Swift, and I really appreciate your insight.

You guys have done a phenomenal job with Zed, and the impact it's having for Rust. But I just want to emphasize on the importance of additionally adopting Swift into your existing development stack -- they each solve a very different subset of challenges, and when used together, they compliment each other in extraordinary ways.

As we continue to build our open source ecosystem, it's imperative that we unify these two languages together, to evolve and empower all developers.

**Comment by ejjonny** [comment]
@furby-tm Any luck? 

I tried to get this running as an extension today. Either I am missing something or sourcekit is.

The majority of requests just happily respond with empty results & sending a `closeDocument` message occasionally crashes the server with no error message.

If anyone has ideas, I am out of them 🙂

Here's my code: https://github.com/ejjonny/swift-ext

![Image 4-26-24 at 5 10 PM](https://github.com/zed-industries/extensions/assets/17223924/d59d0ccf-41f1-4a82-96a0-9056698aa6f6)

Here are the initialization logs:
```
stderr: [2024-04-26 18:46:18.386] SourceKitServer: Request<initialize>(
stderr: id: 0,
stderr: clientID: ObjectIdentifier(0x0000600001319c00),
stderr: params: InitializeRequest(processId: nil, clientInfo: nil, locale: nil, rootPath: nil, rootURI: Optional(LanguageServerProtocol.DocumentURI(storage: file:///Users/ejohn/Documents/zzz/tester)), initializationOptions: nil, capabilities: LanguageServerProtocol.ClientCapabilities(workspace: Optional(LanguageServerProtocol.WorkspaceClientCapabilities(applyEdit: nil, workspaceEdit: Optional(LanguageServerProtocol.WorkspaceClientCapabilities.WorkspaceEdit(documentChanges: Optional(true))), didChangeConfiguration: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: Optional(true))), didChangeWatchedFiles: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: Optional(true))), symbol: Optional(LanguageServerProtocol.WorkspaceClientCapabilities.Symbol(dynamicRegistration: nil, symbolKind: nil)), executeCommand: nil, workspaceFolders: Optional(true), configuration: Optional(true), semanticTokens: nil)), textDocument: Optional(LanguageServerProtocol.TextDocumentClientCapabilities(synchronization: nil, completion: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.Completion(dynamicRegistration: nil, completionItem: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.Completion.CompletionItem(snippetSupport: Optional(true), commitCharactersSupport: nil, documentationFormat: nil, deprecatedSupport: nil, preselectSupport: nil)), completionItemKind: nil, contextSupport: nil)), hover: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.Hover(dynamicRegistration: nil, contentFormat: Optional([LanguageServerProtocol.MarkupKind(rawValue: "markdown")]))), signatureHelp: nil, references: nil, documentHighlight: nil, documentSymbol: nil, formatting: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: nil)), rangeFormatting: nil, onTypeFormatting: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: nil)), declaration: nil, definition: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.DynamicRegistrationLinkSupportCapability(dynamicRegistration: nil, linkSupport: Optional(true))), typeDefinition: nil, implementation: nil, codeAction: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.CodeAction(dynamicRegistration: nil, codeActionLiteralSupport: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.CodeAction.CodeActionLiteralSupport(codeActionKind: LanguageServerProtocol.TextDocumentClientCapabilities.CodeAction.CodeActionLiteralSupport.CodeActionKind(valueSet: [LanguageServerProtocol.CodeActionKind(rawValue: "refactor"), LanguageServerProtocol.CodeActionKind(rawValue: "quickfix"), LanguageServerProtocol.CodeActionKind(rawValue: "source")]))))), codeLens: nil, documentLink: nil, colorProvider: nil, rename: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: nil)), publishDiagnostics: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.PublishDiagnostics(relatedInformation: Optional(true), codeActionsInline: nil, codeDescriptionSupport: nil)), foldingRange: nil, callHierarchy: nil, semanticTokens: nil, inlayHint: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.InlayHint(dynamicRegistration: Optional(false), resolveSupport: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.InlayHint.ResolveSupport(properties: ["textEdits", "tooltip", "label.tooltip", "label.location", "label.command"])))), diagnostic: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.Diagnostic(dynamicRegistration: nil, relatedDocumentSupport: Optional(true)))))), trace: nil, workspaceFolders: Optional([LanguageServerProtocol.WorkspaceFolder(uri: LanguageServerProtocol.DocumentURI(storage: file:///Users/ejohn/Documents/zzz/tester), name: "")]))
stderr: )
stderr: [2024-04-26 18:46:18.392] SourceKitServer: Response<initialize(0)>(
stderr: success(LanguageServerProtocol.InitializeResult(capabilities: LanguageServerProtocol.ServerCapabilities(positionEncoding: nil, textDocumentSync: Optional(LanguageServerProtocol.TextDocumentSync.options(LanguageServerProtocol.TextDocumentSyncOptions(openClose: Optional(true), change: Optional(LanguageServerProtocol.TextDocumentSyncKind.incremental), willSave: Optional(true), willSaveWaitUntil: Optional(false), save: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentSyncOptions.SaveOptions>.value(LanguageServerProtocol.TextDocumentSyncOptions.SaveOptions(includeText: Optional(false))))))), notebookDocumentSync: nil, hoverProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.HoverOptions>.bool(true)), completionProvider: Optional(LanguageServerProtocol.CompletionOptions(resolveProvider: Optional(false), triggerCharacters: Optional(["."]), allCommitCharacters: nil, completionItem: nil, workDoneProgress: nil)), signatureHelpProvider: nil, definitionProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.DefinitionOptions>.bool(true)), typeDefinitionProvider: nil, implementationProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), referencesProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.ReferenceOptions>.bool(true)), documentHighlightProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.DocumentHighlightOptions>.bool(true)), documentSymbolProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.DocumentSymbolOptions>.bool(true)), workspaceSymbolProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.WorkspaceSymbolOptions>.bool(true)), codeActionProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.CodeActionServerCapabilities>.value(LanguageServerProtocol.CodeActionServerCapabilities.supportsCodeActionRequestsWithLiterals(LanguageServerProtocol.CodeActionOptions(codeActionKinds: nil, resolveProvider: nil, workDoneProgress: nil)))), codeLensProvider: nil, documentFormattingProvider: nil, documentRangeFormattingProvider: nil, documentOnTypeFormattingProvider: nil, renameProvider: nil, documentLinkProvider: nil, colorProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), foldingRangeProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), declarationProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), executeCommandProvider: Optional(LanguageServerProtocol.ExecuteCommandOptions(commands: ["semantic.refactor.command"], workDoneProgress: nil)), workspace: Optional(LanguageServerProtocol.WorkspaceServerCapabilities(workspaceFolders: Optional(LanguageServerProtocol.WorkspaceServerCapabilities.WorkspaceFolders(supported: Optional(true), changeNotifications: Optional(LanguageServerProtocol.ValueOrBool<Swift.String>.bool(true)))))), callHierarchyProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), typeHierarchyProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), semanticTokensProvider: nil, inlayHintProvider: nil, diagnosticProvider: nil, selectionRangeProvider: nil, linkedEditingRangeProvider: nil, monikerProvider: nil, inlineValueProvider: nil, experimental: nil)))
stderr: )
```

**Comment by furby-tm** [comment]
@ejjonny hey there! I have yet to take a look at this since the changes they added around how extensions now work in Zed.

I'd like this to be a proper replacement for visual studio code, but I'm not quite sure if Sourcekit-LSP will work well with the existing Zed API or not yet.

However the continuous crashing of the Sourcekit-LSP server does sound familiar to what I remember, hoping that someone might have insight as to why that might be happening.

**Comment by WeetHet** [comment]
> @furby-tm Any luck?
> 
> I tried to get this running as an extension today. Either I am missing something or sourcekit is.
> 
> The majority of requests just happily respond with empty results & sending a `closeDocument` message occasionally crashes the server with no error message.
> 
> If anyone has ideas, I am out of them 🙂
> 
> Here's my code: https://github.com/ejjonny/swift-ext
> 
> ![Image 4-26-24 at 5 10 PM](https://private-user-images.githubusercontent.com/17223924/326139738-d59d0ccf-41f1-4a82-96a0-9056698aa6f6.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTYxNDQsIm5iZiI6MTcxNDg1NTg0NCwicGF0aCI6Ii8xNzIyMzkyNC8zMjYxMzk3MzgtZDU5ZDBjY2YtNDFmMS00YTgyLTk2YTAtOTA1NjY5OGFhNmY2LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDIwNTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTE4M2UyOTk1Y2E4OGQ0YjE3YjRlNzZmYTg1NWY1Yzc5ZDM5NGUyMjhlMmFmM2VmOTEyNTBlMDg3MmVhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.75UPD9vCXkN1Lgw6UZCCkV7gfvH6TCIosgwS1duFtZI)
> 
> Here are the initialization logs:
> 
> ```
> stderr: [2024-04-26 18:46:18.386] SourceKitServer: Request<initialize>(
> stderr: id: 0,
> stderr: clientID: ObjectIdentifier(0x0000600001319c00),
> stderr: params: InitializeRequest(processId: nil, clientInfo: nil, locale: nil, rootPath: nil, rootURI: Optional(LanguageServerProtocol.DocumentURI(storage: file:///Users/ejohn/Documents/zzz/tester)), initializationOptions: nil, capabilities: LanguageServerProtocol.ClientCapabilities(workspace: Optional(LanguageServerProtocol.WorkspaceClientCapabilities(applyEdit: nil, workspaceEdit: Optional(LanguageServerProtocol.WorkspaceClientCapabilities.WorkspaceEdit(documentChanges: Optional(true))), didChangeConfiguration: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: Optional(true))), didChangeWatchedFiles: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: Optional(true))), symbol: Optional(LanguageServerProtocol.WorkspaceClientCapabilities.Symbol(dynamicRegistration: nil, symbolKind: nil)), executeCommand: nil, workspaceFolders: Optional(true), configuration: Optional(true), semanticTokens: nil)), textDocument: Optional(LanguageServerProtocol.TextDocumentClientCapabilities(synchronization: nil, completion: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.Completion(dynamicRegistration: nil, completionItem: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.Completion.CompletionItem(snippetSupport: Optional(true), commitCharactersSupport: nil, documentationFormat: nil, deprecatedSupport: nil, preselectSupport: nil)), completionItemKind: nil, contextSupport: nil)), hover: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.Hover(dynamicRegistration: nil, contentFormat: Optional([LanguageServerProtocol.MarkupKind(rawValue: "markdown")]))), signatureHelp: nil, references: nil, documentHighlight: nil, documentSymbol: nil, formatting: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: nil)), rangeFormatting: nil, onTypeFormatting: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: nil)), declaration: nil, definition: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.DynamicRegistrationLinkSupportCapability(dynamicRegistration: nil, linkSupport: Optional(true))), typeDefinition: nil, implementation: nil, codeAction: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.CodeAction(dynamicRegistration: nil, codeActionLiteralSupport: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.CodeAction.CodeActionLiteralSupport(codeActionKind: LanguageServerProtocol.TextDocumentClientCapabilities.CodeAction.CodeActionLiteralSupport.CodeActionKind(valueSet: [LanguageServerProtocol.CodeActionKind(rawValue: "refactor"), LanguageServerProtocol.CodeActionKind(rawValue: "quickfix"), LanguageServerProtocol.CodeActionKind(rawValue: "source")]))))), codeLens: nil, documentLink: nil, colorProvider: nil, rename: Optional(LanguageServerProtocol.DynamicRegistrationCapability(dynamicRegistration: nil)), publishDiagnostics: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.PublishDiagnostics(relatedInformation: Optional(true), codeActionsInline: nil, codeDescriptionSupport: nil)), foldingRange: nil, callHierarchy: nil, semanticTokens: nil, inlayHint: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.InlayHint(dynamicRegistration: Optional(false), resolveSupport: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.InlayHint.ResolveSupport(properties: ["textEdits", "tooltip", "label.tooltip", "label.location", "label.command"])))), diagnostic: Optional(LanguageServerProtocol.TextDocumentClientCapabilities.Diagnostic(dynamicRegistration: nil, relatedDocumentSupport: Optional(true)))))), trace: nil, workspaceFolders: Optional([LanguageServerProtocol.WorkspaceFolder(uri: LanguageServerProtocol.DocumentURI(storage: file:///Users/ejohn/Documents/zzz/tester), name: "")]))
> stderr: )
> stderr: [2024-04-26 18:46:18.392] SourceKitServer: Response<initialize(0)>(
> stderr: success(LanguageServerProtocol.InitializeResult(capabilities: LanguageServerProtocol.ServerCapabilities(positionEncoding: nil, textDocumentSync: Optional(LanguageServerProtocol.TextDocumentSync.options(LanguageServerProtocol.TextDocumentSyncOptions(openClose: Optional(true), change: Optional(LanguageServerProtocol.TextDocumentSyncKind.incremental), willSave: Optional(true), willSaveWaitUntil: Optional(false), save: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentSyncOptions.SaveOptions>.value(LanguageServerProtocol.TextDocumentSyncOptions.SaveOptions(includeText: Optional(false))))))), notebookDocumentSync: nil, hoverProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.HoverOptions>.bool(true)), completionProvider: Optional(LanguageServerProtocol.CompletionOptions(resolveProvider: Optional(false), triggerCharacters: Optional(["."]), allCommitCharacters: nil, completionItem: nil, workDoneProgress: nil)), signatureHelpProvider: nil, definitionProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.DefinitionOptions>.bool(true)), typeDefinitionProvider: nil, implementationProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), referencesProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.ReferenceOptions>.bool(true)), documentHighlightProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.DocumentHighlightOptions>.bool(true)), documentSymbolProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.DocumentSymbolOptions>.bool(true)), workspaceSymbolProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.WorkspaceSymbolOptions>.bool(true)), codeActionProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.CodeActionServerCapabilities>.value(LanguageServerProtocol.CodeActionServerCapabilities.supportsCodeActionRequestsWithLiterals(LanguageServerProtocol.CodeActionOptions(codeActionKinds: nil, resolveProvider: nil, workDoneProgress: nil)))), codeLensProvider: nil, documentFormattingProvider: nil, documentRangeFormattingProvider: nil, documentOnTypeFormattingProvider: nil, renameProvider: nil, documentLinkProvider: nil, colorProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), foldingRangeProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), declarationProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), executeCommandProvider: Optional(LanguageServerProtocol.ExecuteCommandOptions(commands: ["semantic.refactor.command"], workDoneProgress: nil)), workspace: Optional(LanguageServerProtocol.WorkspaceServerCapabilities(workspaceFolders: Optional(LanguageServerProtocol.WorkspaceServerCapabilities.WorkspaceFolders(supported: Optional(true), changeNotifications: Optional(LanguageServerProtocol.ValueOrBool<Swift.String>.bool(true)))))), callHierarchyProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), typeHierarchyProvider: Optional(LanguageServerProtocol.ValueOrBool<LanguageServerProtocol.TextDocumentAndStaticRegistrationOptions>.bool(true)), semanticTokensProvider: nil, inlayHintProvider: nil, diagnosticProvider: nil, selectionRangeProvider: nil, linkedEditingRangeProvider: nil, monikerProvider: nil, inlineValueProvider: nil, experimental: nil)))
> stderr: )
> ```

This is super weird:
This is the JSON-RPC request sent by neovim, which gets the correct response:
```json
{
  "id": 3,
  "jsonrpc": "2.0",
  "method": "textDocument/hover",
  "params": {
    "position": { "character": 21, "line": 2 },
    "textDocument": {
      "uri": "file:///Users/weethet/Projects/Playgrounds/SwiftPlayground/Sources/main.swift"
    }
  }
}
```
And this request from Zed doesn't:
```json
{
  "jsonrpc": "2.0",
  "id": 65,
  "method": "textDocument/hover",
  "params": {
    "textDocument": {
      "uri": "file:///Users/weethet/Projects/Playgrounds/SwiftPlayground/Sources/main.swift"
    },
    "position": { "line": 2, "character": 18 }
  }
}
```

I don't know why, they seem very similar to me

**Comment by ejjonny** [comment]
I think it has to be some configuration I am missing - I spent some time digging through vscode's swift plugin trying to find hints but I couldn't find anything obvious.

Maybe neovim is passing arguments on sourcekit launch? Or sending different LSP initialization options?

**Comment by furby-tm** [comment]
@WeetHet @ejjonny I'm not sure if it makes a difference or not, but is there any difference between using this instead? (from `xcrun`)

```rs
Ok(zed::Command {
  command: "/usr/bin/xcrun".into(),
  args: vec!["sourcekit-lsp".into(), "--log-level".into(), "debug".into()],
  env: Default::default(),
})
```

**Comment by furby-tm** [comment]
Also, I had noticed you are using the [following revision](https://github.com/ejjonny/swift-ext/blob/main/extension.toml#L9-L11) for `tree-sitter-swift`.


I remember when I had tried to get this to work a while back, I believe I had gotten the best results by using the following revision instead:

```toml
[grammars.swift]
repository = "https://github.com/alex-pinkus/tree-sitter-swift/"
commit = "efa4010dc1c21ef5c63ad2f526909fe44f4a5572"
```

**Comment by ejjonny** [comment]
Okay, looks like sourcekit just requires a certain field that zed is not currently sending in the didOpen message.

Here's the issue for reference.

https://github.com/zed-industries/zed/issues/11399

Full swift support is in sight! 😄

**Comment by furby-tm** [comment]
> Okay, looks like sourcekit just requires a certain field that zed is not currently sending in the didOpen message.
> 
> Here's the issue for reference.
> 
> [zed-industries/zed#11399](https://github.com/zed-industries/zed/issues/11399)
> 
> Full swift support is in sight! 😄
> 
> Thank you for the ideas, all!

**_Very nice!_** 🎉 

I must admit, I'm a bit blind with this -- This is the most I've ever spent looking at **SourceKit-LSP** lol, but that [reference](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem) you added regarding the missing field from the client to the server has got to be it! Epic find! I'm excited to be able to eventually slap VSCode directly into **Trash.app**! 😆

**Comment by ejjonny** [comment]
Just an update on this:
Things are working with the LSP fix so now I'm considering whether to PR the bare-bones LSP extension as-is or try to get the hiccups ironed out first:
- There's an issue with sourcekit diagnostics messages having double escaped forward slashes so errors aren't successfully delivered to Zed.
- The extension assumes your swift installation path & doesn't offer any way to customize.
- The extension doesn't trigger initializer completions on open parenthesis.

**Comment by furby-tm** [comment]
> Just an update on this: Things are working with the LSP fix so now I'm considering whether to PR the bare-bones LSP extension as-is or try to get the hiccups ironed out first:
> 
> * There's an issue with sourcekit diagnostics messages having double escaped forward slashes so errors aren't successfully delivered to Zed.
> * The extension assumes your swift installation path & doesn't offer any way to customize.
> * The extension doesn't trigger initializer completions on open parenthesis.

Awesome! How does one get their extension submitted to Zed's list of predetermined extensions for users to install?

Since the other developer of the current Swift extension stated they don't have support to support this, how can we get your extension to be listed as an installable Zed extension by default (instead of the now unsupported extension).

Thanks!

**Comment by marcusziade** [comment]
> Just an update on this:
> 
> Things are working with the LSP fix so now I'm considering whether to PR the bare-bones LSP extension as-is or try to get the hiccups ironed out first:
> 
> - There's an issue with sourcekit diagnostics messages having double escaped forward slashes so errors aren't successfully delivered to Zed.
> 
> - The extension assumes your swift installation path & doesn't offer any way to customize.
> 
> - The extension doesn't trigger initializer completions on open parenthesis.

There are plenty of issues with Swift anywhere outside Xcode. I write it for hours every week in Cursor, Neovim and Xcode. 

If Zed can be on par with them that's already value adding.

**Comment by ejjonny** [comment]
Good point @marcusziade 🤣
Here's the PR to get it published as-is.
https://github.com/zed-industries/extensions/pull/701

**Comment by furby-tm** [comment]
@ejjonny You're amazing! I really appreciate your time working on this, debugging the extension, and finally figuring out a path forward into getting Swift properly supported in Zed!

> There are plenty of issues with Swift anywhere outside Xcode. I write it for hours every week in Cursor and Neovim.
> If Zed can be on par with them that's already value adding. If Zed can get Swift closer to Go's level, that would be insane.

Currently, the most reliable development experience with Swift, in my opinion, is through **VSCode** using the [Swift extension](https://github.com/swift-server/vscode-swift).

Lately, I've observed significant issues with Xcode's Swift support, especially regarding Swift/C++ interop. Xcode frequently lacks essential features like code completion, "Jump to Definition," and error indication.

What's notable here is that Zed now supports Swift, providing Swift developers with a new choice in code editors. This marks a significant shift for Swift developers and those eager to learn it, offering **development freedom** and a departure from Xcode's restrictive software ecosystem.
