### ISSUE TITLE
Slim

### ISSUE THREAD

**Issue by Atelier-Mirai** [zed-industries/extensions#140]
### Check for existing issues

- [X] Completed

### Language

Slim

### Misc notes

Slim is a template language whose goal is to reduce the view syntax to the essential parts without becoming cryptic. It started as an exercise to see how much could be removed from a standard html template (<, >, closing tags, etc...). 

https://github.com/slim-template/slim

Slim is a great language that converts to HTML without the annoying "<", ">", closing tags, etc.
We hope you will support it.

**Comment by kaspth** [comment]
Looks like the tree-sitter grammar for Slim is here https://github.com/kolen/tree-sitter-slim

**Comment by JosephTLyons** [comment]
There is a [Slim extension](https://github.com/calmyournerves/zed-slim) now.

<img width="1465" alt="SCR-20240716-lyqk" src="https://github.com/user-attachments/assets/681cd83b-6ed4-4bba-8015-5f2b816744ec">
