### ISSUE TITLE
Haxe

### ISSUE THREAD

**Issue by gaetgu** [zed-industries/extensions#142]
### Check for existing issues

- [X] Completed

### Language

Haxe

### Tree Sitter parser link

https://github.com/vantreeseba/tree-sitter-haxe

### Language server link

https://github.com/vshaxe/haxe-language-server

### Misc notes

I really like this language, adding support for it would be awesome. Thanks :)

**Comment by CTC97** [comment]
Throwing my name into the ring for supporters of this!

**Comment by Moshyfawn** [comment]
Note that language extension requests in this repo are community interest, not a request for the Zed team to implement.
