### ISSUE TITLE
Vala

### ISSUE THREAD

**Issue by aleksrutins** [zed-industries/extensions#143]
### Check for existing issues

- [x] Completed

### Language

Vala - <https://vala.dev>

### Tree Sitter parser link

https://github.com/vala-lang/tree-sitter-vala

### Language server link

https://github.com/vala-lang/vala-language-server

**Comment by JosephTLyons** [comment]
There is now a [Vala extension](https://github.com/FyraLabs/zed-vala) that has syntax highlighting and language server support.

<img width="1463" alt="SCR-20240716-lyjk" src="https://github.com/user-attachments/assets/1dbdc07a-a05e-422b-ba35-f0a489f46df8">
