### ISSUE TITLE
LaTeX

### ISSUE THREAD

**Issue by MultisampledNight** [zed-industries/extensions#144]
### Check for existing issues

- [X] Completed

### Language

LaTeX

### Tree Sitter parser link

https://github.com/latex-lsp/tree-sitter-latex

### Language server link

https://github.com/latex-lsp/texlab

### Misc notes

This could go a _long_ way. Many students use LaTeX in order to take notes in lectures, and I think there these things are interesting to look at in addition to the syntax highlighting and LSP itself:

- The ability to add snippets — sure, LaTeX has some of them itself in the form of commands, but it can be _really_ nice to have a nice snippet for typing a table with the `tabular` environment, for example.
- Have some way to look at the final result, nice for typing math equations and similar. Even if it's just the current line in an `align` environment.
- Allow to fold/dim text which is not in the current paragraph/environment.
- SyncTeX support. Part of TeXlive, it allows synchronizing the views of source code and compiled output.

(sidenote: I don't even use Zed yet, though I'd really like to see this some time in future)

**Comment by mocenigo** [comment]
I am very confused. I do not see LaTeX support if I open a LaTeX file into zed.

Tree Sitter parser link

https://github.com/latex-lsp/tree-sitter-latex

Language server link

https://github.com/valentjn/vscode-ltex

Misc notes

It would be nice to add TeX/LaTeX support directly in the main distribution. Besides the vscode-ltex language server there is also
https://github.com/latex-lsp/texlab

**Comment by Moshyfawn** [comment]
> If I click on "unknown" in the bottom right corner, I see a list of languages and TeX or LaTeX are not there.

Have you installed the LaTex extension from `zed: extensions`?

**Comment by mocenigo** [comment]
I did not. Now I have. This is however only syntax highlighting, not compilation commands and preview <-> source sync?

**Comment by Moshyfawn** [comment]
This is the extent of what the Zed language extensions can do at the moment, but there is more to come.

**Comment by mocenigo** [comment]
> This is the extent of what the Zed language extensions can do at the moment, but there is more to come.

The development is happening at an astounding pace.  I am amazed.

**Comment by OliCallaghan** [comment]
Opened up a PR to configure the language server here: https://github.com/rzukic/zed-latex/pull/2.

Note you need texlab installed, if you're on mac, you can run `brew install texlab`.

**Comment by analytic-bias** [comment]
I'd mention also https://www.gnu.org/software/auctex/manual/preview-latex.html. It allows Emacs users to hit a shortcut (or automatically when file saved etc) to render configured LaTeX environments and substitute in the rendered svg in-ppace in the editor. This has been hard to be supported in vscode (https://github.com/James-Yu/LaTeX-Workshop/issues/1427); don't know if you will have any luck.

**Comment by callegar** [comment]
As a LaTeX user, I'd like to add a couple of notes, in case they can be useful for the development of the LaTeX support.

1. There are in fact two different LaTeX syntaxes: the traditional LaTeX2 syntax and the expl3 syntax. The first one is the only one document authors generally deal with. The second one is involved with the LaTeX 3 interfaces and is more and more needed by developers of new packages and classes. The second one differs from the first one as it makes a different use of some characters ('_') mainly, but the role of the space character is changed too and because it is accompanied by style guidelines that prescribe a specific way to practice indentation.  Would be ideal to support both (either with automatic recognition or a switch). What is currently a benchmark for LaTeX support in a programmable editor (emacs + auctex) still has, IMHO, very poor support for expl3, all the time introducing wrong indentation.

2. There are two major ways of doing line wrapping with LaTeX. The traditional one is hard-line-wrapping at word boundaries. It is precisely to support this type of wrapping that TeX makes a single line break in the source substantially equivalent to a space, and two subsequent line breaks significant as a paragraph break.  The other possibility is soft-wrap at word boundaries. This is progressively becoming the new de facto standard, because some LaTeX editors (and prominently online ones, e.g. Overleaf, but also TeXStudio, etc.) tend to work in this way. Clearly, it would be nice to support both, since often you have the need to collaborate on a document where you cannot decide the type of wrapping. The problem is that currently no editor appears to support both wrapping styles correctly wrt indentation.

    - editors initially devised with hard word wrap in mind, typically fail to generate the correct amount of visual indentation when soft wrapping within a group. Typical case are sectioning commands If you have:
        ```LaTeX
        \section{This is a section header with a very very very very very very long title}
        ```
        and the editor soft wraps, you should see
        ```LaTeX
        \section{This is a section header with a
            very very very very very very  long
            title}
        ```
        but you will typically see
        ```LaTeX
        \section{This is a section header with a
        very very very very very very  long
        title}
        ```
        for instance this is the case with emacs+auctex+visual-line-wrap mode. Conversely, these editors are very good at parsing the source considering multiple lines. Sow when using auto hard wrap mode, they are very good at introducing a line break at
        ```LaTeX
        \section{This is a section header with a
        ```
        pushing the `very` on the next line with the correct amount of indentation.
    
    -  editors devised for soft wrapping, conversely all parse LaTeX sources line by line, so when you manually introduce a hard line break they fail to see the number of open braces in the previous lines and do autoindent in the wrong way. Example, I want to define a command for sectioning:
        ```LaTeX
        \newcommand \indepthsection {%
            \section{In depth: #1}%
        }
        ````
        when I press enter at the end of the first line, the editor requires me to manually do the indentation in the following lines.

So LaTeX can be tricky, because actually there are 2 syntaxes and two wrapping styles in use.

**Comment by JosephTLyons** [comment]
There is a [LaTex extension](https://github.com/rzukic/zed-latex) now.

<img width="1465" alt="SCR-20240716-lyyl" src="https://github.com/user-attachments/assets/7b1ee4b5-67a9-4418-8dc0-4ac16c10d68e">

**Comment by lnay** [comment]
> This would definitely be trickier to implement, but in the long term, including a PDF view window would make Zed extremely attractive for this workflow. I'd love to use Zed for typesetting but, even if LSP support was included, I would be reluctant to leave behind the convenient live previewing of the PDF output that VSCode achieves with the Latex Workshop package (or, for Typst, the Typst LSP package).
> <img alt="LaTeX Workshop VSCode screenshot" width="1552" src="https://private-user-images.githubusercontent.com/42874530/301832508-aaef7931-d751-4159-8ee5-2a5f8b011cf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDUwMDIsIm5iZiI6MTcyMzc0NDcwMiwicGF0aCI6Ii80Mjg3NDUzMC8zMDE4MzI1MDgtYWFlZjc5MzEtZDc1MS00MTU5LThlZTUtMmE1ZjhiMDExY2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE3NTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxY2M3ODczZDE0NmY0MjgwNmI1N2MwMGEyZTY4N2M0OWMyMDQ0N2JjZDVkMDBjYjk2ZTliOTNhYmNjNDBhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.djAVXn0ndAstFD4M0qC6VocqJiO1cAybSJ_P-rBZ2U4">

I imagine the internal PDF viewer to be a distraction right now for the Zed team but it's honestly not necessary for LaTeX. You can configure texlab to use a separate pdf viewer and I plan to make some example configs in the LaTeX extension for this kind of thing.

**Comment by mocenigo** [comment]
An exrension to enable LSP support through texlab  can hardly be called TeX/LaTeX support.  An indispensible feature is bidirectional SyncTeX support. You click (+ some modifier, or alternatively you hit a key binding) on the source and you are transported to the corresponding place of the PDF preview, and clicking (+ some modifier) on the preview brings you to the corresponding place in the source. An integrated PDF viewer is not necessary, any external previewer that supports SyncTeX will suffice (I use skim).

Also, maybe the foundation is already there and I just do not know how to enable it, but Zed should have a sidebar that could be configurable with various panes and one could be filled with commands (similar to what latex workshop does for LaTeX in VSCode), including panels of symbols.

This, together with the speed and configurability of Zed would make it the ideal TeX/LaTeX/ConTeXt platform.

**Comment by lnay** [comment]
https://github.com/latex-lsp/texlab/wiki/Previewing
Forwards/inverse search with external pdf viewer is definitely on the table, the symbol pane is not really. Out of interest, with your desires, what do you hope to get in zed that's not in texmaker?

**Comment by lnay** [comment]
Maybe "off the table" is a bit strong, there's only a few things which extension authors can do right now. It's possible that we could see something like the webview ui toolkit from VSCode, but for Zed. But my guess is that something like that would just be more difficult to build with. People have been authoring UIs for the web for decades, nobody outside a few people have been using the "webgpu" thing Zed are working on (which I'm assuming is part of their plan for future graphical extensions).

Outside of the symbol pane, and a multi-file aware outline (we only have that for individual files), I don't see much blocking the zed-latex extension from having almost every other feature you would expect. Mostly leveraging texlab with manual configuration.

**Comment by mocenigo** [comment]
> https://github.com/latex-lsp/texlab/wiki/Previewing Forwards/inverse search with external pdf viewer is definitely on the table, the symbol pane is not really. Out of interest, with your desires, what do you hope to get in zed that's not in texmaker?

I do not use texmaker because it is not native, and it looks and feels very extraneous to the environment. I think snippets are already somehow implemented in Zed, correct? Then I would only need an example or an explanation of how to set them up.

**Comment by lnay** [comment]
With v0.0.7 of the latex extension, snippets should work out of the box. Try typing `\begin`, accept the completion and see if it adds the `\end` with two cursors to type in the environment name. There shouldn't be any need to install texlab yourself for this as Zed should download it automatically. Although I have only tested this myself (x64 Linux and x64 mac). If this doesn't work for you, raise an issue at rzukic/zed-latex with arch+OS and we can work from there.

**Comment by mocenigo** [comment]
> With v0.0.7 of the latex extension, snippets should work out of the box. Try typing `\begin`, accept the completion and see if it adds the `\end` with two cursors to type in the environment name. There shouldn't be any need to install texlab yourself for this as Zed should download it automatically. Although I have only tested this myself (x64 Linux and x64 mac). If this doesn't work for you, raise an issue at rzukic/zed-latex with arch+OS and we can work from there.

This indeed works. But there should be, for mostly textual environments, also autocompletion of words according to a dictionary. VSCode has this, so this is a feature people expect.

**Comment by lnay** [comment]
[Spell checking](https://github.com/zed-industries/zed/issues/5305) appears to be a contentious issue in Zed. There is currently a "Typos" extension however it's not very good at spotting errors.

I would personally like to see Zed run spell checking on sections of the file that the syntax grammar recognises as "spell" areas in a similar way to neovim (with `@spell` and `@nospell` queries). Alternatively, if there ever becomes a story for language servers running on language injections, that could potentially achieve a similar outcome (in this case, a spell checking language server).

**Comment by mocenigo** [comment]
> [Spell checking](https://github.com/zed-industries/zed/issues/5305) appears to be a contentious issue in Zed. There is currently a "Typos" extension however it's not very good at spotting errors.
> 
> I would personally like to see Zed run spell checking on sections of the file that the syntax grammar recognises as "spell" areas in a similar way to neovim (with `@spell` and `@nospell` queries). Alternatively, if there ever becomes a story for language servers running on language injections, that could potentially achieve a similar outcome (in this case, a spell checking language server).

However, I was not referring to spell-checking. Maybe completion was the wrong word, but maybe "suggestions"? Such as, i am typing "typing" and while I am at "ty" a menu appears with "type, types, typing, typology, tycoon" etc. and I can either continue typing, or click on one option, or select it with the up/down arrows, or get rid of the menu with ESC until the end of the word.

**Comment by lnay** [comment]
These two are usually dealt with together (the spell checking and suggestions will use the same dictionary for instance). "Spell-checking" is just the better term to search for developments elsewhere. I do agree that good spelling completions would be nice to have in Zed.

**Comment by mocenigo** [comment]
> These two are usually dealt with together (the spell checking and suggestions will use the same dictionary for instance). "Spell-checking" is just the better term to search for developments elsewhere. I do agree that good spelling completions would be nice to have in Zed.

Exactly. Since one of the goals of Zed is to be adopted (of course!), when we see the marketing of other solutions, the autocompletion/suggestion popup is always a prominent feature. People expect that (like the minimap). I understand that the priorities at the moment are to support all possible AI models, but adding other important UX features should not be delayedm, otherwise there may be an adoption problem (and I am talking seriously, since I really do like Zed).
