### ISSUE TITLE
Nim

### ISSUE THREAD

**Issue by aiakared** [zed-industries/extensions#148]
### Check for existing issues

- [X] Completed

### Language

Nim

### Language server link

https://github.com/PMunch/nimlsp

**Comment by foxoman** [comment]
I do have built nim support here: https://github.com/foxoman/zed-nim, thanks to @alaviss for adding wasm support to nim tree-sitter :)

**Comment by PMunch** [comment]
> I think it would be better to use this https://github.com/nim-lang/langserver instead of the above mentioned nimlsp for Nim. Thank You.

Depends on your definition of better. They both have their pros and cons. Best would be to allow people the choice.

**Comment by zai1208** [comment]
I was just about to add a link to my repo but it doesn't have language server support so @foxoman beat me to it.
Here's the link anyway: https://github.com/zai1208/nim

**Comment by JosephTLyons** [comment]
There is now a [Nim extension](https://github.com/foxoman/zed-nim).
