### ISSUE TITLE
V

### ISSUE THREAD

**Issue by aiakared** [zed-industries/extensions#150]
### Check for existing issues

- [X] Completed

### Language

V

### Tree Sitter parser link

https://github.com/vlang/vls/tree/master/tree_sitter_v

### Language server link

https://github.com/vlang/vls

**Comment by TatoAndTatoOnly** [comment]
The Tree Sitter link is now https://github.com/vlang/v-analyzer/tree/main/tree_sitter_v, and the language server is at https://github.com/vlang/v-analyzer/tree/main .

**Comment by Avey777** [comment]
Can V language be supported as soon as possible?

**Comment by notpeter** [comment]
This was added in

- https://github.com/zed-industries/extensions/pull/765
