### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by walterrowe** [zed-industries/extensions#151]
### Check for existing issues

- [X] Completed

### Language

ansible / YAML

### Tree Sitter parser link

https://github.com/ikatyang/tree-sitter-yaml

### Language server link

https://github.com/redhat-developer/yaml-language-server

### Misc notes

Would like to see ansible / YAML supported.

**Comment by sathishkumar294** [comment]
Any updates?

**Comment by vualett** [comment]
When we can see this implemented on new version of Zed ?

**Comment by ehamiter** [comment]
https://github.com/ArcherHume/jinja2-support

**Comment by maxdeviant** [comment]
There is an Ansible extension available now: https://github.com/kartikvashistha/zed-ansible
