### ISSUE TITLE
QML

### ISSUE THREAD

**Issue by imbev** [zed-industries/extensions#1510]
### Check for existing issues

- [X] Completed

### Language

QML

### Language server link

https://github.com/qt/qtdeclarative/tree/dev/tools/qmlls

### Misc notes

QML is a UI language used for QtQuick application development.

https://doc.qt.io/qt-6/qtqml-tooling-qmlls.html

**Comment by lkroll** [comment]
There already is a QML extension ;)
I just submitted a PR to include LSP support as well.

**Comment by JosephTLyons** [comment]
Looks like the extension exists now, so I'm going to close this issue out!

<img width="828" alt="image" src="https://github.com/user-attachments/assets/96a8a9fb-b176-45c9-b8fb-40564d93ce84">
