### ISSUE TITLE
Fish

### ISSUE THREAD

**Issue by d12bb** [zed-industries/extensions#152]
### Check for existing issues

- [X] Completed

### Language

Fish

### Tree Sitter parser link

https://github.com/ram02z/tree-sitter-fish

### Misc notes

[Fish](https://fishshell.com) the shell, not [><>](https://esolangs.org/wiki/Fish).

**Comment by hasit** [comment]
Fish language support added in #274

**Comment by Moshyfawn** [comment]
#274 has been merged.
