### ISSUE TITLE
GDScript

### ISSUE THREAD

**Issue by Dan2552** [zed-industries/extensions#155]
### Check for existing issues

- [X] Completed

### Language

GDScript

### Language server link

https://github.com/godotengine/godot

### Misc notes

Looks like the language server is with the engine/editor distribution itself 

And looks like there was a bit of history around the language server being implemented in an odd way, but hopefully this resolves it
https://github.com/godotengine/godot/pull/35864

**Comment by JosephTLyons** [comment]
> Got a quick test working locally. Not sure how to publish it to Zed though. Also no LSP support yet as it is not yet opened up by Zed yet (correct me if I'm wrong). <img alt="Screenshot 2024-02-26 at 10 37 51" width="753" src="https://private-user-images.githubusercontent.com/60090827/307736589-f6b9db20-c64b-4cd5-b991-71f976132e0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjQ2NzksIm5iZiI6MTcwODk2NDM3OSwicGF0aCI6Ii82MDA5MDgyNy8zMDc3MzY1ODktZjZiOWRiMjAtYzY0Yi00Y2Q1LWI5OTEtNzFmOTc2MTMyZTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2MTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNWJmMzA5YmVmMjMyZWUyNTc2ZDU0NDJhZjkxNGIwMjY5MWU0NWNhNjllMzdmZmQwNDlmMThjMjA4MWQ0OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.98BtNpxNl9Q3kz2rHUW2sGXCpSIt42WuExiwYDr9Ax4">
> 
> To reproduce it yourself:
> 
> * Build a wasm from https://github.com/PrestonKnopp/tree-sitter-gdscript using `tree-sitter-cli`.
> * Create a `gdscript` extension folder in `/Users/markbrand/Library/Application Support/Zed/extensions/installed` (See other extensions to recreate the folder/file structure)
> * put the compiled wasm under `grammars/gdscript.wasm`
> * copy the `scm` files from https://github.com/helix-editor/helix/tree/6a323c0b1b8fd2491dcbca38b5a1f62bf9581da4/runtime/queries/gdscript in `languages/gdscript/...`
> * Reload Zed

Hey @grndctrl - you can publish by opening a PR within this repo - check out [this PR](https://github.com/zed-industries/extensions/pull/103) as an example.

And yes, you are correct, we don't have language server support in extensions yet, but it is being worked on.

**Comment by grndctrl** [comment]
Thanks @JosephTLyons for pointing me in the right direction, I created a PR #219

**Comment by eth0net** [comment]
@JosephTLyons apologies for the tag, but this one can be closed now right?

I was just looking at working on some of the top requests and don't have a way to close completed ones 👀

**Comment by moomerman** [comment]
@eth0net I think we're waiting for language server support which isn't available to zed extensions yet.

**Comment by eth0net** [comment]
Ah sorry I missed that, my bad! Language servers are now supported however 🚀

**Comment by grndctrl** [comment]
Hi, I'm the one who threw together the GDScript extension, I haven't found the time yet to implement the LSP. I really want to, although I never really built something in Rust. If anyone has a good example from which I can work, I'll try to fit it in my schedule. Or have a stab at it when I'm on paternity leave soon.

**Comment by moomerman** [comment]
> Language servers are now supported however 🚀

ah thanks! I had missed that

**Comment by moomerman** [comment]
@grndctrl I submitted a PR (https://github.com/grndctrl/zed-gdscript/pull/2) with a simple working integration.  Happy to take feedback there, or feel free to use it as a working example to build upon.

**Comment by grndctrl** [comment]
@moomerman Thank you so much! I will look into this later.

**Comment by maxdeviant** [comment]
Language server support was added in https://github.com/zed-industries/extensions/pull/594.

I think we're good to close this out.
