### ISSUE TITLE
Justfile

### ISSUE THREAD

**Issue by d12bb** [zed-industries/extensions#156]
### Check for existing issues

- [X] Completed

### Language

Justfile

### Tree Sitter parser link

https://github.com/IndianBoy42/tree-sitter-just

### Misc notes

Similar enough to makefiles to maybe just use make syntax.

**Comment by jackTabsCode** [comment]
I gave a crack at it here: https://github.com/jackTabsCode/zed-just

but it doesn't work. The file won't associate with the language, and I'm getting this error:
![image](https://github.com/zed-industries/extensions/assets/44332148/6bfb33b5-2df5-465f-ad9c-f1f6849bfbfc)

Source might be here:
https://github.com/IndianBoy42/tree-sitter-just/blob/6c2f018ab1d90946c0ce029bb2f7d57f56895dff/src/scanner.c#L28

I can't make heads or tails of how tree-sitter works, so I was hoping you could help @JosephTLyons?

**Comment by JosephTLyons** [comment]
We'll likely need @maxbrunsfeld's help here.

**Comment by jackTabsCode** [comment]
> We'll likely need @maxbrunsfeld's help here.

I was able to get it to work by forking `tree-sitter-just` and removing the `fprintf` statements.
https://github.com/zed-industries/extensions/pull/478
