### ISSUE TITLE
R

### ISSUE THREAD

**Issue by mr-mobster** [zed-industries/extensions#157]
### Check for existing issues

- [X] Completed

### Language

R

### Tree Sitter parser link

https://github.com/r-lib/tree-sitter-r

### Language server link

https://cran.r-project.org/web/packages/languageserver/index.html

### Misc notes

R is usually written as standalone R scripts `*.R` files or as part of Markdown notebooks/reports (R Markdown) `*.Rmd`, where R code is embedded inside code blocks marked with `{r}`, e.g.:

~~~
```{r}
print("this is some R code")
```
~~~

**Comment by ipstone** [comment]
for helix editor, there is some R language support perhaps we can use as reference to build R support in zed:

https://github.com/helix-editor/helix/tree/master/runtime/queries/r
https://github.com/r-lib/tree-sitter-r

**Comment by ocsmit** [comment]
Hi all, R language support was merged as an extension in #100 and I just opened #656 which adds updated highlighting, outline, and LSP support

**Comment by jtlandis** [comment]
I really like Zed, but as it stands, if I cannot run R code directly from the editor, I will probably prefer RStudio to Zed. RStudio allows for the current line to be executed with `CMD+Enter`, at which point the cursor moves to the next line.

**Comment by JosephTLyons** [comment]
<img width="718" alt="SCR-20240716-lzmm" src="https://github.com/user-attachments/assets/5dd33d25-349c-448d-bd93-e18499e094fe">

**Comment by ocsmit** [comment]
> I really like Zed, but as it stands, if I cannot run R code directly from the editor, I will probably prefer RStudio to Zed. RStudio allows for the current line to be executed with `CMD+Enter`, at which point the cursor moves to the next line.

> @jtlandis these days I mostly use vscode R extension (https://github.com/REditorSupport/vscode-R ), which has really good evaluation/send code blocks to the terminal etc. Together with some keybindings, vscode/R can even mimics nvim-R keybindings.
> 
> I think the vscode R extension would be something that can used as a reference if such functionality would be implemented in zed - wondering if @ocsmit is interested at these?

I fully agree with what has been said about eval/send-code functionality. I have been keeping an eye on the development of the core zed repo, but right now my understanding is there is not a sure fire way to send text to the integrated terminal (although I would love to be wrong!).

**Comment by ocsmit** [comment]
Actually, there is preliminary support for inline code execution through a Jupyter kernel with the [REPL feature](https://zed.dev/docs/repl) (https://github.com/ocsmit/zed-r/issues/1#issuecomment-2231811820). Just tested with the [ark kernel](https://github.com/posit-dev/ark?tab=readme-ov-file) and Zed Preview and works well! Thanks @rgbkrk for bringing to my attention!

For reference this what it looks like in the zed settings to enable. The Ark R-kernel will need to be installed following the instructions on their git page. 
```json
  "jupyter": {
    "enabled": true,
    "kernels": {
      "R": "ark"
    }
  }
```

**Comment by rgbkrk** [comment]
Awesome! I've got some more fixes coming in for the REPL feature, keep the feedback coming with new issues! Feel free to tag with https://github.com/zed-industries/zed/labels/jupyter.

**Comment by h-a-graham** [comment]
@rgbkrk Just had a play with the repl using ark and there is a lot to like! Where is the best place to submit issues on this - in the /zed-industries/extensions repo or elsewhere? Thanks!

**Comment by rgbkrk** [comment]
Hooray! Please report them to zed-industries/zed. There are some known things we will be unable to do (for now), which you can see in the two tracking issues covering Jupyter + Zed:

* https://github.com/zed-industries/zed/issues/9778
* https://github.com/zed-industries/zed/issues/13942

**Comment by tzakharko** [comment]
I’d like to bring to your attention two minor issues I encountered while working with Zed and R. Since I’m not entirely certain about the nature of the problem, I believe this thread is an appropriate forum to discuss it and gather more information. 

1. I get auto-completion suggestions when writing comments,  which can be a bit annoying, as I constantly have to press escape and pay attention to what is being emitted in the editor. Is this an issue with the language server or something within Zed itself? Note that I don't have this behavior working with other LSP-enabled editors like VSCode or Sublime using R's language server.

2.  The R kernel appears to be localized in German for some reason? My machine's locale is set to en_US.UTF-8, so is R.  Here is the locale output from the built-in Zed terminal running R:

    ```
    > Rscript -e "Sys.getlocale()"
    [1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"
    ```

    and here the same from the R REPL within Zed

    ```
    # %%
    Sys.getlocale()
    [1] C/en_US.UTF-8/C/C/C/C
    ```

      I get the correct locale when running an R kernel from Positron (which also uses ark). Any ideas what the issue might be?

I'd be very happy to contribute a patch, and I'd appreciate any leads as to what I should be looking at.

**Comment by rgbkrk** [comment]
> I get auto-completion suggestions when writing comments, which can be a bit annoying, as I constantly have to press escape and pay attention to what is being emitted in the editor.

That's either due to CoPilot/Supermaven (AI Completion) or the R extension https://github.com/ocsmit/zed-r.

**Comment by ndaniel** [comment]
Any *serious* text editor considers this to be the core of programming languages:

- C / C++
- Python
- Java
- JavaScript
- HTML + CSS
- R
- Bash / Shell
- Markdown
- Rust

That’s the minimum core that VS Code, Sublime, Atom, Notepad++, Gedit, and even Kate or Geany already meet.
