### ISSUE TITLE
Perl

### ISSUE THREAD

**Issue by davidolrik** [zed-industries/extensions#158]
### Check for existing issues

- [X] Completed

### Describe the feature

Would love to have Perl support in Zed.

**Comment by rabbiveesh** [comment]
I have opened a PR with perl support; i await it being merged!
https://github.com/zed-industries/extensions/pull/1438

**Comment by rabbiveesh** [comment]
It has now been merged, hurrah! Does that mean we can close this issue?

**Comment by JosephTLyons** [comment]
Sorry, the issue tracker over here doesn't get many eyes on it - closing this out!

<img width="825" alt="SCR-20241110-bnpa" src="https://github.com/user-attachments/assets/67969009-d8a4-450a-bf37-e2de6d0144db">
