### ISSUE TITLE
Cairolang

### ISSUE THREAD

**Issue by koloz193** [zed-industries/extensions#162]
### Check for existing issues

- [X] Completed

### Language

cairo

### Tree Sitter parser link

https://github.com/JoranHonig/tree-sitter-cairo

### Language server link

https://github.com/starkware-libs/cairo/blob/main/vscode-cairo/README.md

### Misc notes

Cairolang is the language used by starknet for their smart contracts.

**Comment by trbutler4** [comment]
hey, ive started working on an this here: https://github.com/trbutler4/zed-cairo

**Comment by JosephTLyons** [comment]
There is a [Cairo extension](https://github.com/trbutler4/zed-cairo) now.

<img width="714" alt="SCR-20240716-lzxx" src="https://github.com/user-attachments/assets/9ee04468-c351-4dc8-96ca-b4d9e4c8f51d">
