### ISSUE TITLE
Twig

### ISSUE THREAD

**Issue by codyhopper** [zed-industries/extensions#163]
### Check for existing issues

- [X] Completed

### Language

Twig

### Tree Sitter parser link

https://github.com/gbprod/tree-sitter-twig

### Misc notes

Twig is a modern template engine for PHP and the primary language for Craft CMS development. 

Also bumped PHP support: https://github.com/zed-industries/zed/issues/5652

**Comment by corneliusio** [comment]
Looks to be added with https://github.com/zed-industries/extensions/pull/575

**Comment by JosephTLyons** [comment]
There is a [Twig extension](https://github.com/YussufSassi/zed-twig) now.

<img width="719" alt="SCR-20240716-maih" src="https://github.com/user-attachments/assets/c91416d3-cd7f-451d-a8a3-9fb3f4200f9f">
