### ISSUE TITLE
Crystal

### ISSUE THREAD

**Issue by marcstein** [zed-industries/extensions#164]
### Check for existing issues

- [X] Completed

### Describe the feature

Any chance of support for the Crystal language?

**Comment by arbales** [comment]
I'd also appreciate Crystal support :)

**Comment by maximvl** [comment]
Upvoting Crystal support as well 👍

**Comment by Qard** [comment]
Seems there's a plugin system now, so presumably someone could pick this up now?

**Comment by xhyrom** [comment]
I'll create zed crystal extension ;)

**Comment by arbales** [comment]
There is one, it’s just not particularly active:
https://github.com/crystal-lang-tools/zed-crystal

**Comment by vualett** [comment]
When we can see this implemented on new version of Zed ?

**Comment by xhyrom** [comment]
> There is one, it’s just not particularly active: https://github.com/crystal-lang-tools/zed-crystal

Oh nice! Then I'll maybe contribute :)

**Comment by JosephTLyons** [comment]
Looks like we have an extension now, so I'm closing this out!

<img width="717" alt="SCR-20241110-boks" src="https://github.com/user-attachments/assets/4de95725-510a-4e69-9979-e0ddb14c5555">
