### ISSUE TITLE
Extension License violation

### ISSUE THREAD

**Issue by equinusocio** [zed-industries/extensions#1645]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This situation does not constitute a bug; rather, it is a substantial violation of the commercial license by an unauthorized extension. The extension [published by Codextor](https://github.com/codextor/zed-material-theme) is intentionally infringing upon the license of the original Material Theme released back in 2016 developed for Visual Studio Code and other software applications.

<details><summary>Material Theme (and Derivates) commercial license</summary>
<p>

```
English Version: Commercial License for "Material Theme" and Derivatives
--------------------------------------------------------
1. Usage License
   This agreement grants the user a non-exclusive, non-transferable, and revocable commercial license to install and use the "Material Theme" extension on unlimited devices for business purposes. The user is not authorized to modify, distribute, resell, or lease the extension without the author’s written consent.

2. Restrictions
   The user agrees not to:
   a) Reverse engineer, modify, decompile, or disassemble the extension's source code.
   b) Use the extension for illegal or unauthorized activities.
   c) Share the extension through channels other than the official sales channel.
   d) Republish the extension, even with a different name or with substantial modifications, for free or for a fee, for Visual Studio Code or other software, without the author's written consent.
   e) Create derivative, copy, or replica extensions that may confuse users into thinking they are the original extension or an official update.
   f) Use similar names or trademarks that could cause confusion with the original extension or lead to a mistaken association with it.
   g) Use the extension in combination with other products or services to create integrated solutions without the author's written consent.
   h) Subject the extension to benchmarking or performance evaluation tests for comparative or public purposes without the author’s written authorization.
   i) Register or attempt to register any part of the extension as their own trademark, intellectual property, or patent.
   j) Transfer licensing rights to third parties or sublicense the extension.
   k) Use or distribute the extension in cloud computing environments, SaaS (Software as a Service) distribution, or shared platforms without written approval.
   l) Use the extension to create misleading or fraudulent content, or in a way that could harm the product's or the author's reputation.

3. Intellectual Property
   All rights, title, and interest in the "Material Theme" extension remain with the author. The user acquires no intellectual property rights in the extension.

4. Updates and Support
   The author may, at their discretion, provide updates or fixes for the extension. Updates may be subject to additional terms.

5. Confidentiality
   The user agrees to treat any technical or business information related to the extension as confidential unless authorized in writing by the author.

6. Warranties and Limitation of Liability
   The software is provided "as is" without any warranties, expressed or implied. The author is not liable for any direct, indirect, or consequential damages resulting from the use of the software.

7. Term and Termination
   The license is valid from the purchase date and remains effective unless the user breaches the terms of this agreement. The author reserves the right to revoke the license in case of violation.
```

</p>
</details> 

## Violation points
> 2.c) Share the extension through channels other than the official sales channel.

This doesn't need explanations

> 2.d) Republish the extension, even with a different name or with substantial modifications, for free or for a fee, for Visual Studio Code or other software, without the author's written consent.

The developer didn't ask for consent or reach us before publishing its extension

>2.e) Create derivative, copy, or replica extensions that may confuse users into thinking they are the original extension or an official update.

Using same name, logo, screenshot, colors, variant names, the author created a replica extension and publishing it as the original Extension.

> 2.f) Use similar names or trademarks that could cause confusion with the original extension or lead to a mistaken association with it.

Similar to 2.e

> 2.j) Transfer licensing rights to third parties or sublicense the extension.

The developer is basically redistributing the intellectual property under an open-souce license, changing and violating the original one.

> 2.l) Use the extension to create misleading or fraudulent content, or in a way that could harm the product's or the author's reputation.

The developer is harming the product by sharing a free version of the theme (see replica extension above). 

---

The Material Theme constitutes a paid extension. So the version published by Codextor is an unauthorized reproduction The version disction undermines our efforts and negatively impacts the users who compensate for it. We have previously [contacted the author](https://github.com/Codextor/zed-material-theme/issues/1) and requested the removal of the extension; however, we hereby appeal to you to take appropriate measures to remove or rename it if the author fails to heed this request. 

## Solutions

1. Remove the extension
2. Rename the extension and remove any reference (logo, screenshot, etc.. included) to the original theme, to solve the license violation above.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups/screenshots to help explain and present your vision of the feature

![Screenshot 2024-11-08 at 19 06 35](https://github.com/user-attachments/assets/2334751a-8d33-4e48-aab1-2956d46306b7)

**Comment by Codextor** [comment]
As the author of the extension in question, I've posted my response [here](https://github.com/Codextor/zed-material-theme/issues/1#issuecomment-2489681638), to the issue opened by @equinusocio on the extension's GitHub repository.
In my response, I clarified that the license referenced by @equinusocio in the comment above does not match the license that ships with the Material Theme — Free extension version 34.7.5. This can be verified by installing the extension from the Visual Studio Code Marketplace and checking the `LICENSE.txt` file included with it.

**Comment by equinusocio** [comment]
This is the only answer I'll give since i'v already proposed multiple solutions above.

## Point 1
You are using the same name, same colors, same color combinations, same variants names, Even the same preview screenshots. **This is not taking inspiration.**

## Point 2
From the license YOU mentioned, you are violating the following points.

> 1. ...The user is not authorized to _modify_, _distribute_, resell, or rent the extension _without the written consent of the author._
> 2. Restrictions
   The user may not:
   a) Reverse engineer, modify, decompile, or disassemble the extension's source code.
   b) Use the extension for illegal or unauthorized activities.
   c) Share the extension through channels other than the official sales channel.
> 4. Intellectual Property
   Mattia Astorino holds all rights, titles, and interests related to the extension, including but not limited to copyright, patents, trademarks, and trade secrets.


- 1 — You dind't asked for any authorization to re-distribuite the extension.
- 2.1 — By distributing it with the same name, but open source, you'are actually changing the extension.
- 2.c — You are sharing/distributing (github and zed marketplace) the extension as open source through non-official sales channels.
- 4 — By using the same name, colors, color combinations, screenshots, variants name your are taking on intellectual property.

Lastly, forking/copying, and distributing other people licensed closed-source code doesn't make it yours.

## Would you like to keep your extension? Change the extension name, variants name, screenshots, and keep a reference to the original Material Theme. Easy solution.

**Comment by notpeter** [comment]
Hi @equinusocio,

A [preserved fork of your repository](https://github.com/Dramaga11/vsc-material-theme) contains the [Apache2 license](https://github.com/Dramaga11/vsc-material-theme/blob/main/LICENSE) as recently August 2024.
Codextor/zed-material-theme is also available under the [Apache2 license](https://github.com/Codextor/zed-material-theme/blob/main/LICENSE).

That license contains the following provision:

> 2. Grant of Copyright License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form.

As a result, the fact that you currently distribute your theme under an alternate non-free license likely has no bearing on this matter. The rights granted by the Apache2 license do not terminate when you change your mind.  I am inclined to assume that @Codextor has prepared a derivative work in compliance with the rights you granted him under the terms of the Apache2 license.

Furthermore, the fact that you (1) deleted your git history in an attempt to scrub any mention of the Apache2 license, (2) failed to mention this in your allegations above, and (3) subsequently made multiple [substantive modifications your license terms](https://github.com/material-theme/vsc-material-theme/compare/b755fb804a4916d97977416a8c406e6b2cb42cef...882aa498f55ef4970d347de46f1a8385820c2e84) in the hours after opening this issue to better support your allegation of "license violation" demonstrate a pattern of bad faith, disingenuous communications.  

Such actions are extremely unprofessional, a violation of the [Zed Code of Conduct](https://zed.dev/code-of-conduct) and will not be tolerated.

**Comment by equinusocio** [comment]
I'm unprofessional because i'm fighting to preserve my rights, my work, that's your opinion. 

I found unprofessional and childish that you close an issue with a lazy comment, with YOUR interpretation of a license, instead of apply what the license SAYS and ALLOWS, and completely ignoring paragraph 4.

>2. What is being granted? Each _contributor_ (anyone who contributes to the project covered by this license) grants you (the user or recipient of the software) a copyright license.

Read what "contributor" means in the license. 

#### Who is a Contributor?
A "Contributor" is defined in the Apache License as someone who:
Authors original parts of the software, or
Submits modifications or contributions (e.g., bug fixes, features) that are accepted into the project by the maintainers.


#### Who grants the license?
Section 2 states that each Contributor grants the license to you. This means:
Only those who contributed to the project (e.g., wrote code, documentation, or other content) are granting you rights.
Non-contributors (e.g., users or distributors who merely pass along the software without modifying or contributing to it) are not in a position to grant these rights because they don’t hold the copyright.

---

## 4. Redistribution. 

You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:

- You must give any other recipients of the Work or Derivative Works a copy of this License; and
- You must cause any modified files to carry prominent notices stating that You changed the files; and
- You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and

**All the 4. points points are respected here**

--- 

## More free info for you.

The fork you mentioned is not distributing the software (as we know), and is not violating anything. You clearly, don't know what you're talking about.


Said that is clear that the zed industries promote license violations. So bad for the whole industry and for everyone who care about their work. Still in beta and already toxic.

**Comment by JamesClarke7283** [comment]
> I'm unprofessional because i'm fighting to preserve my rights, my work, that's your opinion.
> 
> I found unprofessional and childish that you close an issue with a lazy comment, with YOUR interpretation of a license, instead of apply what the license SAYS and ALLOWS, and completely ignoring entire sections.
> 
> > 2. What is being granted? Each _contributor_ (anyone who contributes to the project covered by this license) grants you (the user or recipient of the software) a copyright license.
> 
> Read what "contributor" means in the license. The author doesn't; fall under the contributor definition. Anyone who forked without contribution (a fork is not a contribution) doesn't fall under the contribution term defined by the license.
> 
> SPOILER
> ## 4. Redistribution.
> You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
> 
> * You must give any other recipients of the Work or Derivative Works a copy of this License; and
> * You must cause any modified files to carry prominent notices stating that You changed the files; and
> * You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
> 
> **All the above points from chapter 4 are not respected here**. There are no prominent notices one changed files and there is no attribution, copyright in the source code.
> 
> This extension is clearly not a fork or a re-distributed software. It's an attempt to get on intellectual property.
> 
> ## More free info for you.
> The fork you mentioned is not distributing the software (as we know), and is not violating anything. You clearly don't know what you're talking about.
> 
> Said that is clear that the zed industries promote license violations. So bad for the whole industry and for everyone who care about their work. Still in beta and already toxic.

Correct me if I am wrong, but. The version they used was the Apache2.0 licensed version. I don't see how that violates anything.

Again, let me know if you have evidence to the contrary.

**Comment by nicc777** [comment]
@equinusocio Did you realize you are violating your own license? 

> c) Share the extension through channels other than the official sales channel.

FYI - GitHub is not a sales channel. It's a Git repo, and your project is public. Further more, many of the terms does not even make sense and you may be in violation of GitHub [terms of service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users). For example, you state:

> e) Create derivative, copy, or replica extensions that may confuse users into thinking they are the original extension or an official update.

But the GitHub terms of service state that the rights you automatically grant to other users including "_By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control)._".

If you really want to add a restrictive license, you should either make your repo private or remove it completely from GitHub.

There is absolutely nothing you can do or enforce  anything for the work done previously while it was still license under the Apache license.  In fact, don't be surprised if another community now just carry on with the development on one of these open source versions.

**Comment by daiyam** [comment]
> Read what "contributor" means in the license. The author doesn't; fall under the contributor definition. 

This is the most funny because here is the definition of `Contributor`:
> "Contributor" shall mean Licensor and any individual or Legal Entity
> on behalf of whom a Contribution has been received by Licensor and
> subsequently incorporated within the Work.

What's the Licensor?
> "Licensor" shall mean the copyright owner or entity authorized by
> the copyright owner that is granting the License.

It's the author.

**Comment by HengiFettlich** [comment]
The new license agreement also violates EU laws. Prohibiting users from reverse engineering for the purpose of fixing bugs is against EU legislation, see C-13/20 CJEU.

**Comment by dko1905** [comment]
@equinusocio has had this issue blow up in his face.

Here's a short list of what he's done:

1. Claiming Apache 2.0 doesn't permit redistribution, forks or derivations, which is *clearly* false
2. Possibly not complying with GitHub ToS by not allowing forks
3. Changing to a proprietary (partially?) uninforcible license by disallowing reverse engineering 
4. Being a total crybaby about the situation and resorting to deleting evidence of the project previously being Apache licensed.

What a clown 🤡

**Comment by notpeter** [comment]
Hundreds of people found this issue and were classy enough not to comment.

But y'all five watched a [Theo Browne clip](https://www.youtube.com/watch?v=3wz7YF2as-c) cut from a month old livestream and couldn't help but insert yourself into a resolved conversation from 40days ago to which you were not a party. Such comments are unwelcome, unprofessional and a violation of the [Zed COC](https://zed.dev/code-of-conduct).

@JamesClarke7283 @nicc777 @daiyam @HengiFettlich and @equinusocio: Do better.

Locking this issue to prevent future brigading.
