### ISSUE TITLE
Slint

### ISSUE THREAD

**Issue by xpader** [zed-industries/extensions#166]
### Check for existing issues

- [X] Completed

### Language

Slint

### Tree Sitter parser link

*No response*

### Language server link

https://github.com/slint-ui/slint/blob/master/tools/lsp/README.md

### Misc notes

Rust GUI - Slint UI Language LSP support request.

**Comment by Moshyfawn** [comment]
@maxdeviant, it appears that the Slint extension is now in the repository, but it has not yet been reflected in the extensions store. Is there a release process that must be completed before extensions become visible?

**Comment by maxdeviant** [comment]
> @maxdeviant, it appears that the Slint extension is now in the repository, but it has not yet been reflected in the extensions store. Is there a release process that must be completed before extensions become visible?
> 
> Ref: #355

Currently only Zed v0.129.x (currently on Nightly) can see extensions that provide language servers, as they depend on a new major version of the extension schema.

These will be available to the Preview release channel on Wednesday, and then on Stable the following week.

**Comment by Moshyfawn** [comment]
> Currently only Zed v0.129.x (currently on Nightly) can see extensions that provide language servers, as they depend on a new major version of the extension schema.

Ah, I missed the part where it has the LSP integration. Thanks 🙏

**Comment by Moshyfawn** [comment]
I believe the extensions support LSP now, so I'll close this issue out. You can find the Slint extension in the Extensions tab in Zed.
