### ISSUE TITLE
Asciidoc

### ISSUE THREAD

**Issue by clsource** [zed-industries/extensions#168]
### Check for existing issues

- [X] Completed

### Language

Asciidoc

### Misc notes

Asciidoc have similar syntax to Markdown. 
It is used for writing technical documentations as an alternative to Markdown.

- File extensions: `asciidoc, adoc`

**Comment by andreicek** [comment]
I've submitted #419 which adds very basic support for AsciiDoc. We are limited to what the upstream tree sitter implementation supports but it works to some extent.

**Comment by JosephTLyons** [comment]
There is an [AsciiDoc extension](https://github.com/andreicek/zed-asciidoc) now.

<img width="716" alt="SCR-20240716-mawc" src="https://github.com/user-attachments/assets/b2e6416d-2db9-4405-9779-bbb5d417466f">
