### ISSUE TITLE
How do I locally test an extension?

### ISSUE THREAD

**Issue by jackTabsCode** [zed-industries/extensions#17]

**Comment by maxdeviant** [comment]
If you add the extension to the  `~/Library/Application\ Support/Zed/extensions/installed/` directory then it will show up in Zed.

It should pick it up automatically, but you may also need to run `zed: reload extensions` in order for it to see it.

For extensions that contain grammars you would need to manually build the WASM grammar using the `build-wasm` command in the Tree-sitter CLI.

**Comment by jackTabsCode** [comment]
@maxdeviant Thanks for the swift response! This should be included in the README for authoring extensions!

**Comment by jackTabsCode** [comment]
> Having some reference material for how to build tree sitter grammars locally would be useful as well

Yeah.. honestly I don't have any experience with wasm so I wouldn't even know where to start.

**Comment by maxdeviant** [comment]
> Having some reference material for how to build tree sitter grammars locally would be useful as well; since these are referenced as an extension referencing another git url, it's not obvious what steps one should take

Right now the best way would be to look at how we build the WASM grammars when we package the extensions: https://github.com/zed-industries/extensions/blob/main/script/package-extensions#L230

It currently requires a pre-release version of the Tree-sitter CLI (there’s a binary available on npm), and you need to have the Emscripten SDK on your path (or have Docker available and it will be handled automatically).

We’ll have more docs coming soon on writing/testing extensions.
