### ISSUE TITLE
Blade

### ISSUE THREAD

**Issue by james2doyle** [zed-industries/extensions#176]
### Check for existing issues

- [X] Completed

### Language

blade

### Tree Sitter parser link

https://github.com/EmranMR/tree-sitter-blade

### Language server link

https://github.com/haringsrob/laravel-dev-tools

### Misc notes

Currently the file opens as PHP which is half right. Just needs support for the actual blade syntax now

**Comment by JosephTLyons** [comment]
There is a [Blade extension](https://github.com/bajrangCoder/zed-laravel-blade) now.

<img width="720" alt="SCR-20240716-mcaq" src="https://github.com/user-attachments/assets/00dfedf9-7db4-4ab8-a35f-6591c7213c23">
