### ISSUE TITLE
Ron

### ISSUE THREAD

**Issue by zaycev** [zed-industries/extensions#182]
### Check for existing issues

- [X] Completed

### Language

RON

### Tree Sitter parser link

https://github.com/amaanq/tree-sitter-ron

### Misc notes

Please add support for [RON](https://github.com/ron-rs/ron) file format.

**Comment by JosephTLyons** [comment]
There is a [Ron extension](https://github.com/onbjerg/zed-ron) now.

<img width="721" alt="SCR-20240716-mcll" src="https://github.com/user-attachments/assets/1c741974-a712-4c22-98db-ae5c4c40a9d1">
