### ISSUE TITLE
Helm

### ISSUE THREAD

**Issue by ndgoodman** [zed-industries/extensions#186]
### Check for existing issues

- [X] Completed

### Language

Helm

### Language server link

https://github.com/mrjosh/helm-ls

**Comment by erste** [comment]
I've tried to create syntax highlighting extension https://github.com/erste/zed-helm using this fork of go-template grammar https://github.com/qvalentin/tree-sitter-go-template

It works but not quite as it should:
* The language of *.yaml files always switches to YAML and there is no way to override this behavior.
* Commenting doesn't always work.

**Comment by vualett** [comment]
When we can see this implemented on new version of Zed ?

**Comment by suzaku** [comment]
Without K8s and Helm support, I'll have to continue using VSCode.

**Comment by neurogoblin** [comment]
Would it be simpler to contribute to [this Helm Tree-sitter grammar](https://github.com/Giedriusj1/helm-tree-sitter)?

**Comment by marclop** [comment]
I'd love to see helm support for Zed.

**Comment by crabique** [comment]
@marclop Helm extension has been merged today: https://github.com/zed-industries/zed/blob/main/docs/src/languages/helm.md#setup

**Comment by marclop** [comment]
@crabique Thanks! It works great so far.

**Comment by JosephTLyons** [comment]
Looks like we have an extension now, so I'm closing this out!

<img width="718" alt="SCR-20241110-bsjv" src="https://github.com/user-attachments/assets/7e5dfac4-73e5-49f0-9cc5-505406584ae4">
