### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by robguthrie** [zed-industries/extensions#189]
### Check for existing issues

- [X] Completed

### Language

Pug

### Tree Sitter parser link

https://github.com/zealot128/tree-sitter-pug

### Misc notes

Pug is a markup language that outputs HTML. It's similar in intent to HAML and Slim.

I use Pug in my Vue component files:

```
<template lang="pug">
div(attr="something") hello world
</template>
```

It would be wonderful if Zed supported this. Is the provided tree-sitter highlighting any help?

**Comment by rendomnet** [comment]
This is MUST!

**Comment by ruslankorsar** [comment]
The only thing that stops me from fully using Zed

**Comment by JosephTLyons** [comment]
Looks like we have an extension now, so I'm closing this out!

<img width="722" alt="SCR-20241110-brws" src="https://github.com/user-attachments/assets/d6971396-0dbe-46eb-b196-0e7e02568270">

**Comment by zolotokrylin** [comment]
Awesome!

**Comment by stenolmre** [comment]
I'm not sure this is actually resolved or completed. Maybe pug files have right color coding but vue files do not. I think the original idea or request from the author was to have colors in vue template. With the plugin I do not have colors.

![vue-template](https://github.com/user-attachments/assets/66388f32-552f-4d77-bf29-b05d30fd680f)

**Comment by repoman** [comment]
> I'm not sure this is actually resolved or completed. Maybe pug files have right color coding but vue files do not. I think the original idea or request from the author was to have colors in vue template. With the plugin I do not have colors.
> 
> ![vue-template](https://private-user-images.githubusercontent.com/60060439/385910228-66388f32-552f-4d77-bf29-b05d30fd680f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1Mjg2NzQsIm5iZiI6MTczMTUyODM3NCwicGF0aCI6Ii82MDA2MDQzOS8zODU5MTAyMjgtNjYzODhmMzItNTUyZi00ZDc3LWJmMjktYjA1ZDMwZmQ2ODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDIwMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyY2UwYTdkYjYyNmQzNjE2MmFhMTcwY2M2NGRkM2FjMTVkZTEwMjYxNzc5NWQyNTNhMjNlM2E3MjU0MDc1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rKVXVewn6MR-q8VaLrv3ReH21hIAUmL83VSnTYvCi1o)

I fixed this particular issue with Pug markup inside Vue component files here: https://github.com/zed-extensions/vue/pull/7
