### ISSUE TITLE
Templ

### ISSUE THREAD

**Issue by prnk28** [zed-industries/extensions#191]
### Check for existing issues

- [X] Completed

### Language

Templ

### Tree Sitter parser link

https://github.com/vrischmann/tree-sitter-templ/tree/master

### Language server link

https://marketplace.visualstudio.com/items?itemName=a-h.templ

**Comment by joerdav** [comment]
Looks like this was resolved from a syntax highlighting perspective in https://github.com/zed-industries/extensions/pull/232 we just need lsp support now!

**Comment by joefitzgerald** [comment]
LSP support was added via https://github.com/makifdb/zed-templ/pull/2.

**Comment by JosephTLyons** [comment]
There is a [Templ extension](https://github.com/makifdb/zed-templ) now.

<img width="716" alt="SCR-20240716-mcvr" src="https://github.com/user-attachments/assets/594839b6-1fbe-477b-a1b1-c6fad0426774">
