### ISSUE TITLE
Roc

### ISSUE THREAD

**Issue by h2000** [zed-industries/extensions#192]
### Check for existing issues

- [X] Completed

### Language

ROC

### Tree Sitter parser link

https://github.com/faldor20/tree-sitter-roc

### Language server link

https://github.com/roc-lang/roc

### Misc notes

At the moment the ROC treesitter works for rust with my patched version:  https://github.com/h2000/tree-sitter-roc/tree/master. I have send a PR for this.

**Comment by maxdeviant** [comment]
A Roc extension is now available: https://github.com/zed-industries/extensions/pull/432.
