### ISSUE TITLE
Handlebars

### ISSUE THREAD

**Issue by antepenavasyfl** [zed-industries/extensions#193]
### Check for existing issues

- [ ] Completed

### Describe the feature

I use for my templates handlebars.js would be nice to have support for that

**Comment by kanejamison** [comment]
Would love to see this since it's the default templating language on Ghost CMS - https://ghost.org/docs/themes/

**Comment by kanejamison** [comment]
I see this was marked as closed as it related to Ember but currently HBS files don't seem to have an association in Zed by default, and Handlebars is used by a number of non-Ember languages and projects.

Any chance we can re-open this @maxdeviant ?

It seems people in the #417 discussion are still confused by this as well.

**Comment by kanejamison** [comment]
For anyone else that comes along this, here's the project settings.json to temporarily match your .hbs files to .html, which highlights everything except your handlebars code:

```
 "file_types": {
    "HTML": ["hbs"]
  }
```

Like this:

![Image](https://github.com/user-attachments/assets/eee17206-6173-40f6-867a-1e382f3a08dd)

**Comment by phtdacosta** [comment]
any news on getting **.hbs** support?
