### ISSUE TITLE
Groovy/Jenkinsfile

### ISSUE THREAD

**Issue by saada** [zed-industries/extensions#195]
### Check for existing issues

- [X] Completed

### Language

Groovy

**Comment by IstvanCsVarga** [comment]
We got Groovy but what about Jenkinsfiles?

**Comment by vuon9** [comment]
@maxdeviant Groovy is only half of the issue. Should this be re-opened?

**Comment by maxdeviant** [comment]
> [@maxdeviant](https://github.com/maxdeviant) Groovy is only half of the issue. Should this be re-opened?

Please open a new issue.

**Comment by vuon9** [comment]
<img width="496" height="77" alt="Image" src="https://github.com/user-attachments/assets/098d0976-d234-4d69-9712-a637d216680d" />
