### ISSUE TITLE
WGSL

### ISSUE THREAD

**Issue by mintyleaf** [zed-industries/extensions#198]
### Check for existing issues

- [X] Completed

### Language

WGSL

### Tree Sitter parser link

https://github.com/szebniok/tree-sitter-wgsl

### Language server link

https://github.com/wgsl-analyzer/wgsl-analyzer

**Comment by JosephTLyons** [comment]
There is a [Wgsl extension](https://github.com/luan/zed-wgsl) now.

<img width="716" alt="SCR-20240716-mdlz" src="https://github.com/user-attachments/assets/7ad9d328-a173-43be-8602-946193a296ca">
