### ISSUE TITLE
Jsonnet

### ISSUE THREAD

**Issue by aarongodin** [zed-industries/extensions#201]
### Check for existing issues

- [X] Completed

### Describe the feature

Jsonnet is a configuration language that has an LSP: https://github.com/grafana/jsonnet-language-server

It would be helpful to have jsonnet support in Zed.

**Comment by raymond-xu-gtg** [comment]
Would love to use Zed for Jsonnet works!

**Comment by katawasiya** [comment]
Jsonnet is an excellent type of data storage and transmission. I really want to see it in the equally beautiful ZED IDE :)
