### ISSUE TITLE
macOS theme

### ISSUE THREAD

**Issue by dwt** [zed-industries/extensions#21]
### Check for existing issues

- [X] Completed

### Describe the feature

I am missing a theme that just renders as close as possible like a native macOS app. Preferably with light and dark mode support.

None of the current themes look native to MacOS, the window and tabs look off, the sidebar looks off the highlight color is not  respected, you know, all the little tings that make MacOS MacOS.

### If applicable, add mockups / screenshots to help present your vision of the feature

Well, I would guess you could have a look at TextMate, they already do this pretty nicely.
<img width="884" alt="image" src="https://github.com/zed-industries/zed/assets/57199/751737d9-866b-458a-83f6-60ed6e91545d">

**Comment by d1y** [comment]
https://github.com/huacnlee/zed-theme-macos-classic

**Comment by JosephTLyons** [comment]
Closed via:

- https://github.com/zed-industries/extensions/pull/54
