### ISSUE TITLE
Odin

### ISSUE THREAD

**Issue by hqnna** [zed-industries/extensions#222]
### Check for existing issues

- [X] Completed

### Language

Odin

### Tree Sitter parser link

https://github.com/laytan/odin-tree-sitter

### Language server link

https://github.com/DanielGavin/ols

**Comment by maxdeviant** [comment]
There was previously a PR opened to add Odin before Zed had extension support: https://github.com/zed-industries/zed/pull/7094.

It could be a good starting point for someone interested in adding Odin support.

**Comment by clseibold** [comment]
Since an Odin plugin has been added to the repo, I think this can be closed now. @maxdeviant

**Comment by maxdeviant** [comment]
As @clseibold mentioned above, there is now an Odin extension available: https://github.com/zed-industries/extensions/pull/539
