### ISSUE TITLE
Nord

### ISSUE THREAD

**Issue by dsully** [zed-industries/extensions#25]
### Check for existing issues

- [X] Completed

### Describe the feature

Please add the Nord theme: https://www.nordtheme.com to Zed.

**Comment by JosephTLyons** [comment]
Hello @dsully, I've transferred your issue into the `extensions` repository and have reopened it. There is an extension on the store that has a Nord theme bundled:

- https://github.com/ssaunderss/zed-nightfox/

But I'm not quite sure it meets your request, so I'm leaving the issue open.

**Comment by obahareth** [comment]
Perhaps this could do the trick?
https://github.com/mikasius/zed-nord-theme

If it's alright with @mikasius

**Comment by mikasius** [comment]
@obahareth I've added this theme to zed's extensions repo. :) 
Waiting for review.

**Comment by JosephTLyons** [comment]
Closing out in favor of @mikasius' extension!
