### ISSUE TITLE
Rosé Pine (default, Dawn, and Moon)

### ISSUE THREAD

**Issue by Jacobikinz** [zed-industries/extensions#258]
### Check for existing issues

- [X] Completed

### Misc notes

https://rosepinetheme.com/

**Comment by Moshyfawn** [comment]
There's already a Rosé Pine theme family included in Zed by default.

<img width="1136" alt="image" src="https://github.com/zed-industries/extensions/assets/16290753/878cb3e7-1af2-4401-b75f-65ffdfee3b74">
