### ISSUE TITLE
Cappuccin theme

### ISSUE THREAD

**Issue by BlackGoku36** [zed-industries/extensions#26]
### Check for existing issues

- [X] Completed

### Describe the feature

Theme support for https://github.com/catppuccin/catppuccin
Examples for IDE: https://github.com/catppuccin/catppuccin#-ports-and-more

**Comment by JosephTLyons** [comment]
Hey @BlackGoku36, I moved this issue to the `extensions` repo and reopened it. This issue is closed via the Zed plugin:

- https://github.com/ssaunderss/zed-catppuccin
