### ISSUE TITLE
Fish extension doesn't load

### ISSUE THREAD

**Issue by piechologist** [zed-industries/extensions#275]
Opening a fish file causes this error in the Zed log and the extension vanishes from the list of installed languages:
```log
2024-03-02T05:32:47+01:00 [ERROR] crates/extension/src/extension_store.rs:569: failed to load extension.json

Caused by:
    No such file or directory (os error 2)
2024-03-02T05:32:52+01:00 [INFO] installing extension fish 0.0.1
2024-03-02T05:32:53+01:00 [ERROR] crates/extension/src/extension_store.rs:569: TOML parse error at line 11, column 27
   |
11 | increase_indent_pattern = "^\\s*((\\b(else|function|if|while|for|switch|case|begin)\\b((?!\\b(end)\\b).)*)|(\\(\\s*))$|\\\\$"
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
regex parse error:
    ^\s*((\b(else|function|if|while|for|switch|case|begin)\b((?!\b(end)\b).)*)|(\(\s*))$|\\$
                                                             ^^^
error: look-around, including look-ahead and look-behind, is not supported
```

Zed: v0.124.8 (Zed)
OS: macOS 12.7.3
Memory: 8 GiB
Architecture: x86_64

I deleted the two lines with the offending regex patterns in `~/Library/Application Support/Zed/extensions/installed/fish/languages/fish/config.toml` and restarted Zed. Seems ok then.

Implemented with #274. Thank you @hasit for your efforts!

**Comment by hasit** [comment]
@piechologist

Thanks for reporting it. Looks like Zed doesn't support backreference. I will fix it.

**Comment by hasit** [comment]
@piechologist 

https://github.com/zed-industries/extensions/pull/278 is the fix with the problematic regex removed. I'd be open to some help on that.

I also brought in [bracket config](https://github.com/piechologist/zed-fish/blob/main/languages/fish/config.toml#L6) from your repo.

**Comment by piechologist** [comment]
@hasit 

I borrowed the bracket config from [Zed's bash implementation](https://github.com/zed-industries/zed/blob/main/crates/languages/src/bash/config.toml). I forgot to add braces expansion in my repo. Would you mind adding it?

```
{ start = "{", end = "}", close = true, newline = false },
```

I can't think of a perfect solution for indentation without a look-ahead pattern but this might come close:

```regex
# Indent if the line starts with a keyword that must be followed by one or more parameters *or*
# if the line starts and ends with `begin` or `else` *or*
# if the line ends with an opening parentheses or a backslash.
increase_indent_pattern = "^\\s*(function|if|while|for|switch|case)\\b|^\\s*(begin|else)\\s*$|[(\\\\]\\s*$"

# Dedent if the line begins with a keyword that ends a block or a closing parentheses.
decrease_indent_pattern = "^\\s*(((else|case|end)\\b)|\\))"```
```

That won't cover cases like putting `for i in 1 2 3; echo $i; end` on a single line but what's perfect in this world?

Regarding indentation, I added Fish's own prettifier to my `~/.config/zed/settings.json`:

```json
  "language_overrides": {
    "Fish": {
      "formatter": {
        "external": { "command": "fish_indent", "arguments": [] }
      }
    }
  }
```

That works well when saving the file or hitting Shift-Cmd-I. I don't know how to put it into an extension though.

TBH, I have no idea how to improve the tree-sitter part. The [Helix editor](https://github.com/helix-editor/helix/tree/master/runtime/queries/fish) does it well but that's beyond me.

Hope I haven't bombarded you with too many thoughts. Let me know if I should open a PR on your repo. I appreciate that you're taking the time to make this extension.

**Comment by JosephTLyons** [comment]
Hey @hasit, has this been fixed? I noticed this merged PR:

https://github.com/zed-industries/extensions/pull/278

Just wondering if we should close this out or keep it open.

**Comment by hasit** [comment]
@JosephTLyons

The initial issue of fish extension not loading as been fixed in #278. We can open another issue to track the discussion about enhancements proposed by @piechologist or we can take it to the [zed-fish](https://github.com/hasit/zed-fish) repo.

**Comment by hasit** [comment]
@piechologist 

I added missing bracket config as part of a new commit. Let's track the indentation changes on [zed-fish](https://github.com/hasit/zed-fish). I'd be happy and open to PRs since you are working on it.

**Comment by JosephTLyons** [comment]
Sounds good! I'll close this issue out.
