### ISSUE TITLE
Oceanic Next

### ISSUE THREAD

**Issue by jchaing** [zed-industries/extensions#28]
### Check for existing issues

- [X] Completed

### Describe the feature

Kindly requesting to add Oceanic Next Theme support 🤞

https://github.com/voronianski/oceanic-next-color-scheme

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://user-images.githubusercontent.com/9937696/236305481-cd5e0f67-3bec-4901-bfd9-d63920b2c85f.png)

**Comment by JosephTLyons** [comment]
Hello @jchaing, I've transferred your issue into the `extensions` repository and have reopened it.

**Comment by JosephTLyons** [comment]
A [Oceanic Next theme extension](https://github.com/rkunev/oceanic-next) now exists.

<img width="720" alt="SCR-20240716-mktk" src="https://github.com/user-attachments/assets/12cadfb7-85b0-4596-af23-3963de13d7cb">
