### ISSUE TITLE
Cannot highlight import statements

### ISSUE THREAD

**Issue by zarifpour** [zed-industries/extensions#282]
I have tried modifying the `highlights.scm` file to set `import` as a `@keyword` as done here for typescript: https://github.com/zed-industries/zed/blob/a17c207217f69df0d3dd843183ae8739f92ccb60/crates/languages/src/typescript/highlights.scm

I even completely overwrote the file to match 1:1 with the file above.

---

I can't seem to highlight `import` as it is for other languages.

---

Edit: The repo I'm testing with is https://github.com/zarifpour/zed-solidity

**Comment by piechologist** [comment]
Are you sure the grammar exposes `import`? Open a solidity file and try Zed's `debug: open syntax tree view` command. You can click on an `import` statement and check the tree view. Very handy.

**Comment by zarifpour** [comment]
Very handy indeed! What do you think?

![CleanShot 2024-03-05 at 12 48 52 on Zed — zed-solidity@2x](https://github.com/zed-industries/extensions/assets/16494335/00ac4e92-2c8b-4800-a5fb-15dea6791704)

**Comment by piechologist** [comment]
LGTM. I'd try `(import_directive "import" @include)`. Alternatively, `(import_directive) @include` should cover all child nodes.

If you want to dive in, the [tree-sitter docs about queries](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries) are quite comprehensive.

**Comment by zarifpour** [comment]
So it looks like it's being detected correctly, but the color is set to white. 

Any idea how to explicitly set this... It's odd  because in other languages, i.e. typescript, the color is purple for me and I'm assuming that it should be the same type of token here.

**Comment by zarifpour** [comment]
![CleanShot 2024-03-05 at 13 30 33 on Zed — test sol — zed-solidity@2x](https://github.com/zed-industries/extensions/assets/16494335/23f9f322-7905-402d-87fb-b69770af7569)

![CleanShot 2024-03-05 at 13 27 50 on Zed — test ts — zed-solidity@2x](https://github.com/zed-industries/extensions/assets/16494335/9e0ad86d-502a-4716-a434-9e28a3fc8dca)

**Comment by zarifpour** [comment]
Three things I'm weighing in my head:
- is this a zed config issue (i don't think so)
- is this a zed language server issue - not being supported (maybe)
- is this a highlights.scm issud (maybe)

**Comment by piechologist** [comment]
My best guess: 

1. The compiled grammar (referenced by the TOML file) parses and validates your source code and makes a tree. That's the one you can see in the tree view. There's an `ERROR` in your screenshot of test.sol. You can't capture error nodes. Always test with valid code like example.sol in your very first screenshot. 

2. A query in highlights.scm consults the tree and assigns a capture e.g., `@keyword`.

3. Zed looks for a syntax token in your active theme. For instance, the color for `@keyword` is `#73ade9` in the default One Dark theme. If there's no `@include` token in the theme, you'd probably get a default like white.

Start with an easy query and a common syntax token like `(import_directive) @keyword`. Consult the docs I mentioned above and look at queries in other languages as you did with TS and fine-tune your query. I'm not an expert on this though, just started two days ago.

**Comment by zarifpour** [comment]
Spot on. Thank you!

I had to update my theme to include imports:

![CleanShot 2024-03-05 at 16 59 20 on Zed — StWA sol — 21LST-1@2x](https://github.com/zed-industries/extensions/assets/16494335/94241323-80b7-4bc5-94d9-5a2278cfbbdc)

```json
"include": {
  "color": "#c678ddff", // purple
  "font_style": null,
  "font_weight": null
}
```
