### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by kobzar** [zed-industries/extensions#29]
### Check for existing issues

- [X] Completed

### Describe the feature

Please add Material color theme

**Comment by JosephTLyons** [comment]
Hello @kobzar, I've transferred your issue into the `extensions`. repository and have reopened it.

**Comment by xerodark** [comment]
@kobzar I just had my rendition of Material Dark theme added to `extensions/`. Feel free to check it out and let me know your thoughts!

**Comment by kobzar** [comment]
Thanks ! This is it!
