### ISSUE TITLE
.ASM theme

### ISSUE THREAD

**Issue by BenCaunt** [zed-industries/extensions#317]
### Check for existing issues

- [X] Completed

### Misc notes

I've had a great time using Zed so far.  I do a lot of embedded programming and am currently a computer engineering student so having an assembly theme would be great!

**Comment by BenCaunt** [comment]
I see I might have misused this.  I meant .asm syntax highlighting -- not a theme called .ASM sorry.

**Comment by JosephTLyons** [comment]
@BenCaunt - we do have an assembly extension!

<img width="1136" alt="SCR-20240308-jwut" src="https://github.com/zed-industries/extensions/assets/19867440/cf9f4304-a45c-4893-ba28-bffa03123fa7">
