### ISSUE TITLE
Shopify Liquid language support

### ISSUE THREAD

**Issue by RomainDW** [zed-industries/extensions#331]
### Check for existing issues

- [X] Completed

### Language

Liquid

### Tree Sitter parser link

https://github.com/Shopify/tree-sitter-liquid

### Language server link

https://shopify.dev/docs/themes/tools/cli/language-server

**Comment by jeffreyguenther** [comment]
Looks like that tree-sitter grammar has been archived. There is a recent fork: https://github.com/hankthetank27/tree-sitter-liquid.

This is what nvim-treesitter references.

Also, here's a direct link to the [LSP package](https://github.com/Shopify/theme-tools/tree/main/packages/theme-language-server-node)

Depending on how this extension is implemented, it might need to use that package directly. Using the Shopify CLI will bring with it a bunch of other tooling that might not be needed. 

Close inspection is needed.

**Comment by Symediane** [comment]
Is it planned to have the same functionality as the VSCode extension?

- Code formatting
- Code completion and documentation on hover
- Liquid tag, filter and object
- HTML tag, attribute and value
- Theme, section and block settings
- Theme translation
- Render tag snippet
- Code navigation
- Auto-closing pairs
- Theme checks and fixes

**Comment by jeffreyguenther** [comment]
@Symediane I'd love for the extension to have all the same functionality. The tools are available to make it possible.

I personally don't have a concrete plan to tackle the rest of the build at the moment. More likely, I'll chip away at things over time. I'm totally game to accept PRs or sponsorships that would allow me to dedicate the time to the work.

**Comment by mufftee** [comment]
We need this so badly 😄

**Comment by jeffreyguenther** [comment]
We do! It would make using Zed a dream for Shopify development. Let's see what I can do after Editions.

**Comment by Sanj718** [comment]
Thank you! the syntax highlighter is already great move and help! Will be waiting for further improvements! Thank you so much @jeffreyguenther

**Comment by JosephTLyons** [comment]
There is now a [Liquid extension](https://github.com/TheBeyondGroup/zed-shopify-liquid/blob/main/extension.toml).

<img width="715" alt="SCR-20240716-mfee" src="https://github.com/user-attachments/assets/5699ddb9-6b28-4b9e-bad7-69cbf70676ac">

**Comment by RomainDW** [comment]
I don't think the extension was finished; it seems to me that the aim was to add the features listed by @Symediane

**Comment by jeffreyguenther** [comment]
Ya, that's correct. I started with Liquid syntax highlighting and am working towards creating an extension that does similar things to the official Shopify VSCode plugin. PRs are welcome on that repo. I'm chipping away at things between other projects.
