### ISSUE TITLE
Re-add `gentle-dark`

### ISSUE THREAD

**Issue by maxdeviant** [zed-industries/extensions#332]
@brianjgamble We had to pull the `gentle-dark` extension (#321) since it has a malformed `extension.json` that slipped through our validation.

The `author` field should be `authors` and contain an array:

https://github.com/gentlelionstudios/gentle-dark-zed/blob/a0fc3981e072df6a86175456af426dae6d17748b/extension.json#L4

If you fix that up and resubmit we can add it again 🙂

**Comment by brianjgamble** [comment]
Sorry about that. 😓 
Here's the new PR: https://github.com/zed-industries/extensions/pull/334

**Comment by maxdeviant** [comment]
All good! We're going to be improving our CI soon to make it more comprehensive with its checks to prevent stuff like this from being missed by reviewers.

Gentle Dark is available now:

<img width="506" alt="Screenshot 2024-03-13 at 8 27 14 AM" src="https://github.com/zed-industries/extensions/assets/1486634/3cd00c6c-fea4-40e8-aa5a-9b909ab42b76">
