### ISSUE TITLE
Java indentation problem

### ISSUE THREAD

**Issue by mshashikanth7** [zed-industries/extensions#341]
### Check for existing issues

no full support for java! extenssion doest provide full support

### Language

JAVA

**Comment by maxdeviant** [comment]
@mshashikanth7 Could you please provide some more detail as to the issue you are experiencing?

**Comment by mshashikanth7** [comment]
there is no full langauge support for java yet! the extension only provides code highlighting

**Comment by valentinegb** [comment]
You should checkout [ABckh/zed-java-language-support-jdtls](https://github.com/ABckh/zed-java-language-support-jdtls) ;)

**Comment by mshashikanth7** [comment]
finally! i can switch :)
