### ISSUE TITLE
Aura

### ISSUE THREAD

**Issue by birobirobiro** [zed-industries/extensions#36]
### Check for existing issues

- [X] Completed

### Describe the feature
Please add the **Aura Theme** to Zed.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/extensions/assets/22185823/5e238b3c-a55f-4cb3-adf5-c393351d552b)

> https://github.com/daltonmenezes/aura-theme

**Comment by dustessavdh** [comment]
Hi,
I've created a PR (https://github.com/daltonmenezes/aura-theme/pull/212) in the aura theme repo to include zed support.

However, I've had some trouble creating a PR for this repo to add it to the list.
I managed to add the repo as a submodule and using sparse-checkout I managed to only include the zed package.
The problem I'm seeing is that the files will be under `packages/zed` and not in the root of the submodule.
Does this matter? Or does someone know how to fix this?

**Comment by dustessavdh** [comment]
I think I've figured it out! I can set the path for the extention in the `extenions.toml` file just like for all extensions coming from the zed repo.
E.g. https://github.com/zed-industries/extensions/blob/f2f4299b064f8ae30ba7df853ad189ffea468c03/extensions.toml#L23
