### ISSUE TITLE
Polar

### ISSUE THREAD

**Issue by obahareth** [zed-industries/extensions#38]
### Check for existing issues

- [X] Completed

### Misc notes

Add the Polar theme (light version of Nord theme).

This repo is a good starting point:
https://github.com/mtyn/polar

**Comment by blaqat** [comment]
Working on [this port](https://github.com/bIaqat/polar-theme-zed/tree/main)
<p float="left">
  <img src="https://github.com/user-attachments/assets/20895290-55e3-47b6-ac57-4c60c77f47da"/>
</p>

**Comment by blaqat** [comment]
This theme extension has been merged, can be closed if everything looks alright!

**Comment by JosephTLyons** [comment]
Looks like we have this extension now, closing this issue out!

<img width="719" alt="image" src="https://github.com/user-attachments/assets/a6cffe79-16c6-4d58-836a-4908b28105b2">
