### ISSUE TITLE
OneHunter

### ISSUE THREAD

**Issue by teziovsky** [zed-industries/extensions#39]
### Check for existing issues

- [X] Completed

### Describe the feature
Please add the OneHunter Themes to Zed. Especially Vercel theme 🥰

### If applicable, add mockups/screenshots to help present your vision of the feature
<img width="742" alt="Screenshot 2024-02-16 at 23 43 05" src="https://github.com/zed-industries/extensions/assets/36273653/da24cd12-17a8-43af-86ff-8cf97a831893">

<img width="744" alt="Screenshot 2024-02-16 at 23 39 22" src="https://github.com/zed-industries/extensions/assets/36273653/985f1379-1f5e-481f-bdb6-fc3990d8a91d">

<img width="731" alt="Screenshot 2024-02-16 at 23 43 37" src="https://github.com/zed-industries/extensions/assets/36273653/c62e67f6-bf70-4c14-a2d9-c8f54cd6cf25">

<img width="733" alt="Screenshot 2024-02-16 at 23 43 53" src="https://github.com/zed-industries/extensions/assets/36273653/f4ff8a0f-8f50-4299-83a8-98e0be695d25">

> [https://marketplace.visualstudio.com/items?itemName=RaillyHugo.one-hunter](https://marketplace.visualstudio.com/items?itemName=RaillyHugo.one-hunter)

**Comment by d1y** [comment]
This theme looks very good. I will help you create three of them: https://note.ms/sepk

**Comment by teziovsky** [comment]
Thank you so much 🥰

**Comment by teziovsky** [comment]
Is there any progress on this theme?
