### ISSUE TITLE
LSP support for Nix

### ISSUE THREAD

**Issue by srid** [zed-industries/extensions#395]
### Check for existing issues

- [X] Completed

### Describe the feature

LSP support for Nix would be great.

- https://github.com/oxalica/nil
- https://github.com/nix-community/rnix-lsp
- https://github.com/nix-community/nixd

ctx: https://github.com/zed-industries/zed/issues/5895#issuecomment-1908718458

**Comment by Moshyfawn** [comment]
Successor of #268

**Comment by JosephTLyons** [comment]
It seems like the [Nix extension](https://github.com/zed-extensions/nix) now has language server support via [`nixd`](https://github.com/nix-community/nixd).

<img width="715" alt="SCR-20240716-mfrl" src="https://github.com/user-attachments/assets/1ae64393-c882-4a39-8907-d3665f848b59">
