### ISSUE TITLE
Palenight

### ISSUE THREAD

**Issue by esauri** [zed-industries/extensions#40]
### Check for existing issues

- [X] Completed

### Misc notes

Palenight theme, by [Olaolu Olawuyi](https://github.com/whizkydee).

VSCode version: https://github.com/whizkydee/vscode-palenight-theme

![theme preview](https://i.imgur.com/G3KSdGo.png)

**Comment by JosephTLyons** [comment]
A [Palenight Theme extension](https://github.com/alanmontgomery/palenight-zed) now exists.

<img width="720" alt="SCR-20240716-mmfh" src="https://github.com/user-attachments/assets/bf5c1ae9-18d1-466f-9b35-a930d8c88dca">
