### ISSUE TITLE
Horizon

### ISSUE THREAD

**Issue by esauri** [zed-industries/extensions#41]
### Check for existing issues

- [X] Completed

### Misc notes

Horizon light & dark themes

https://horizontheme.netlify.app/

VSCode version: https://github.com/alexandernanberg/horizon-theme-vscode

![theme preview](https://raw.githubusercontent.com/jolaleye/horizon-theme-vscode/master/preview.png)

**Comment by sidsbrmnn** [comment]
https://github.com/ayn2op/zed-horizon

Thanks to @ayn2op you can now use Horizon theme by installing it from extensions.
