### ISSUE TITLE
Poimandres theme

### ISSUE THREAD

**Issue by ahmed-altariqi** [zed-industries/extensions#47]
### Check for existing issues

- [X] Completed

### Misc notes

https://github.com/drcmda/poimandres-theme

**Comment by tika** [comment]
Any ideas why this theme looks strange with Python?
<img width="369" alt="Screenshot 2024-03-09 at 19 41 20" src="https://github.com/zed-industries/extensions/assets/48658947/a644a430-cce8-4b2c-ac4a-88db9ae866d1">

**Comment by ahmed-altariqi** [comment]
It looks just fine on VSC!

<img width="363" alt="py-demo" src="https://github.com/zed-industries/extensions/assets/144698244/67c85599-b1eb-4205-b76e-052858fda799">
