### ISSUE TITLE
CSV (column-based highlighting)

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/extensions#475]
### Check for existing issues

- [X] Completed

### Language

CSV

### Tree Sitter parser link

?

### Language server link

?

### Misc notes

We have a CSV extension now, but it highlights items based on type:

<img width="829" alt="SCR-20240411-mvco" src="https://github.com/zed-industries/extensions/assets/19867440/82b74301-076b-4ea1-be13-bc88dbaf73a2">

It would be cool to havea CSV extension that highlights based on column, like [CSV Rainbow](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv) from VS Code:

<img width="805" alt="SCR-20240411-mwkq" src="https://github.com/zed-industries/extensions/assets/19867440/d5d721c9-18f9-481d-ab41-f6eae15dae76">

**Comment by weartist** [comment]
I can do this, and if I need to be an extension, I'll need to look at the instructions

**Comment by weartist** [comment]
@JosephTLyons  I'd love to provide a CSV extension to support different colors and table editing, I checked the extension's documentation, and wanted to make sure that at the moment we can only get some of the functions of tree-sitter through extensions, and where can I learn about the new API opening related to extensions

**Comment by JosephTLyons** [comment]
> @JosephTLyons I'd love to provide a CSV extension to support different colors and table editing, I checked the extension's documentation, and wanted to make sure that at the moment we can only get some of the functions of tree-sitter through extensions, and where can I learn about the new API opening related to extensions

Hey @weartist - sorry for the confusion here - extensions currently only support themes and languages - I created these issues so I could remove an issue in the zed repo about this. This column-based CSV extension could possibly be built right now, but the table editor certainly can't. I've added an `awaiting infrastructure` to signal that these types of extensions can't be built yet.

**Comment by weartist** [comment]
> > @JosephTLyons I'd love to provide a CSV extension to support different colors and table editing, I checked the extension's documentation, and wanted to make sure that at the moment we can only get some of the functions of tree-sitter through extensions, and where can I learn about the new API opening related to extensions
> 
> Hey @weartist - sorry for the confusion here - extensions currently only support themes and languages - I created these issues so I could remove an issue in the zed repo about this. This column-based CSV extension could possibly be built right now, but the table editor certainly can't. I've added an `needs infrastructure` to signal that these types of extensions can't be built yet.

Thanks for the help, it seems that only some tree-sitter features can be used at the moment, I have raised the price of a rainbow csv based on tree-sitter, and if there are other new capabilities available, I will try to submit the extension of form editing

**Comment by JosephTLyons** [comment]
There is now a really great [Rainbow CSV extension](https://github.com/weartist/zed-rainbow-csv) available.

<img width="712" alt="SCR-20240716-mgmx" src="https://github.com/user-attachments/assets/9a20c148-b7d1-4a4b-8dae-1db7d330fffa">
