### ISSUE TITLE
Jinja2 templates

### ISSUE THREAD

**Issue by anilmuppalla** [zed-industries/extensions#487]
### Check for existing issues

- [X] Completed

### Describe the feature

jinja2 file extention is not part of the supported file formats. 

### If applicable, add mockups / screenshots to help present your vision of the feature

asd

**Comment by ArcherHume** [comment]
@anilmuppalla I've added an extension for Jinja2 support which you can find by searching "Jinja2 Template Support" in the Zed extensions.

**Comment by anilmuppalla** [comment]
you are a legend @ArcherHume, I just tried it and love it! Thank you
