### ISSUE TITLE
Request to Add Twig Templating Language Support

### ISSUE THREAD

**Issue by Jelmer-Ketelaar** [zed-industries/extensions#488]
### Check for existing issues

- [X] Completed

### Describe the feature

The feature request revolves around the integration of Twig, a flexible, fast, and secure template engine for PHP, into the Zed code editor. This integration aims to significantly enhance Zed's versatility and appeal to web developers, especially those working within the Symfony and Drupal ecosystems, where Twig is extensively utilised.

**Comment by JosephTLyons** [comment]
Closing in favor of #163. Note that someone has opened up a PR here, to add a Twig extensions:

- https://github.com/zed-industries/extensions/pull/486
