### ISSUE TITLE
PowerShell

### ISSUE THREAD

**Issue by martinhiriart** [zed-industries/extensions#496]
### Check for existing issues

- [X] Completed

### Language

PowerShell

### Tree Sitter parser link

https://github.com/PowerShell/tree-sitter-PowerShell

### Language server link

https://github.com/PowerShell/PowerShellEditorServices

**Comment by tomtorggler** [comment]
Any news on this one? vscode is killing my battery in real time and on my search for an alternative I landed here. Thanks.
