### ISSUE TITLE
Add discord rich presence

### ISSUE THREAD

**Issue by dimkauzh** [zed-industries/extensions#499]
### Check for existing issues

- [X] Completed

### Describe the feature

Hey, so I could you maybe add discord rich presence to Zed? Basicly discord rich presence is this thingy that shows up in your profile (see picture). You could maybe add it as a option so user can enable it if he wants or not. It would be great if it could be added, its pretty easy to implement. Thanks!

Btw sorry that the picture is in Ukrainian a little bit.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="303" alt="Screenshot 2023-09-10 at 16 34 41" src="https://github.com/zed-industries/community/assets/106883655/d030603c-410e-473f-bb3f-bca590a73dcb">

**Comment by xHyroM** [comment]
I'm working on discord presence extension for Zed using LSP. 

repo: https://git.sr.ht/~hyro/zed-discord-presence
github mirror: https://github.com/xHyroM/zed-discord-presence

In few hours i'll publish release with the LSP to make everything works, gonna sleep now.
![image](https://github.com/user-attachments/assets/519afb5b-8220-4d04-a268-89c4d2564d17)

**Comment by xHyroM** [comment]
the extension should work :+1:

**Comment by dimkauzh** [comment]
> I'm working on discord presence extension for Zed using LSP (until there'll be better extension support, then i'll rewrite it)
> 
> repo: https://github.com/xHyroM/zed-discord-presence
> 
> In few hours i'll publish release with the LSP to make everything works, gonna sleep now.
> ![image](https://github.com/user-attachments/assets/ebdc77fb-2d4c-4563-95e7-0d297eadff97)
> 

AMAZING WORK DUDE! Good job!!!!

**Comment by xhyrom** [comment]
> AMAZING WORK DUDE! Good job!!!!

Thank you so much! You can give a ⭐ if you want :D

**Comment by dimkauzh** [comment]
> > AMAZING WORK DUDE! Good job!!!!
> 
> Thank you so much! You can give a ⭐ if you want :D

Almost forgot hehehe

**Comment by xhyrom** [comment]
Added support for recognizing languages in [v0.4.0](https://github.com/xhyrom/zed-discord-presence/releases/tag/v0.4.0)

![image](https://github.com/user-attachments/assets/511c9f9f-74ba-4596-aec1-0616876f1abd)

**Comment by dimkauzh** [comment]
> Added support for recognizing languages in [v0.4.0](https://github.com/xhyrom/zed-discord-presence/releases/tag/v0.4.0)
> 
> ![image](https://private-user-images.githubusercontent.com/56601352/354928086-511c9f9f-74ba-4596-aec1-0616876f1abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MDkxNDIsIm5iZiI6MTcyMjgwODg0MiwicGF0aCI6Ii81NjYwMTM1Mi8zNTQ5MjgwODYtNTExYzlmOWYtNzRiYS00NTk2LWFlYzEtMDYxNjg3NmYxYWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDIyMDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZmRjNmM0MWM3NjMzODM4ZDMwMmEyMDZkN2Y5ZGQ2MTM5NTAxNTVhZTc4NjhhYjk0YjhlOGYxZTI0ZDMyMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g4ngOtDlzPCJp0uTM9tdxiMFAHmTDaVo3OwhKqjOjEw)

I tried it today, works amazing! Good job mate!

**Comment by dimkauzh** [comment]
Yohoo! We got it!

**Comment by dxrkinfuser44** [comment]
i know this is digging up an ancient ancient issue but did you ever get around to making that extension instead of using an lsp server? i wanna config the rich presence icon to be more than just showing the file name and such

**Comment by xhyrom** [comment]
> i know this is digging up an ancient ancient issue but did you ever get around to making that extension instead of using an lsp server? i wanna config the rich presence icon to be more than just showing the file name and such

It’s unfortunately not possible to build that extension without using an LSP server because of limitations in Zed’s API.

Also if you have any feature requests or ideas, you can propose them directly in the extension’s repository here:
https://github.com/xhyrom/zed-discord-presence
