### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/extensions#500]
**Describe the solution you'd like**
Would be great to have Java support, at least syntax highlight. LSP integration is a (very) nice to have.

**Comment by pedrosmmc** [comment]
I would say, obviously, for a Java developer syntax highlight isn't enough! 😒
Probably some minimal features like LSP, code inspection, code format, etc.
Well, I'll stick with NeoVim or IntelliJ for now...

**Comment by mohamnag** [comment]
It’s a pity but looks like it’s decided not to support Java. So be it.

**Comment by mikayla-maki** [comment]
We're happy to support Java :) 

We're just moving the locus of responsibility out of our hands and into the extension system.

**Comment by RayBytes** [comment]
> We're happy to support Java :)
> 
> We're just moving the locus of responsibility out of our hands and into that of the community, via the extension system.

extensions do not provide near enough at this moment to consider it "supporting" java, even if the language server was added to that extension.

**Comment by mikayla-maki** [comment]
what’s missing to support java?

**Comment by JosephTLyons** [comment]
> > We're happy to support Java :)
> > We're just moving the locus of responsibility out of our hands and into that of the community, via the extension system.
> 
> extensions do not provide near enough at this moment to consider it "supporting" java, even if the language server was added to that extension. Zed is great, but I can't really use it as much as I may want to if it doesn't really care about that language. Please give official support of Java.

I'm not sure what all you might be referencing here, but I'm assuming some of what you are looking for is general tooling, like being able to run your code in Zed, debugger, etc. These are things we are working on, but they aren't specific to Java, so they aren't really tied into this issue at all.

**Comment by mikayla-maki** [comment]
As far as I know, all languages are being moved to extensions. We might maintain some of them in-house, so we can bundle them into Zed at build time. But beyond long term support like that, we don’t plan on granting special privileges to certain extensions over others.

**Comment by ABckh** [comment]
Closing this PR because of the newly added [Java Eclipse JDTLS extension](https://github.com/zed-industries/extensions/pull/632)

**Comment by ABckh** [comment]
Hello, Java extension with LSP can be installed and used:

<img width="1337" alt="Screenshot 2024-05-01 at 6 53 06 PM" src="https://github.com/zed-industries/extensions/assets/88387714/6dfd6440-c8c6-4237-9fb1-534dd855b131">

**Comment by quot** [comment]
> How do I "run" it?

Build and debug support is currently the most voted for issue in the main Zed repo. https://github.com/zed-industries/zed/issues/5065

If I had to guess, this feature will be added for officially supported languages first, then built out to allow for extensions to use the feature, and then the developers of the Java extension would need to implement that feature. It's probably going to be a while.

For now, it's pretty easy to set up tasks to build/run whatever you want. It's no where near what a full IDE can do, but it handles just about everything I need while I am actively working on a project. https://zed.dev/docs/tasks

**Comment by swpalmer-cl** [comment]
> Probably the Eclipse JDT is the way to go, VSCode uses that too.

Not a good reason. VSCode using it's "official" Java support (I think done by RedHat) makes a total mess of things.  Writing class files in non-standard locations requiring updates to .gitignore rules and generally being a pain.  I prefer the NetBeans version.

**Comment by TharinduEpaz** [comment]
please add java support
