### ISSUE TITLE
Docker & Docker Compose support

### ISSUE THREAD

**Issue by ghost** [zed-industries/extensions#504]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

Checked, no duplicate

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Dockerfile & docker-compose.yml files are extremely common in my work and having syntax support would be great! I would hope for the following features (in order of what I priority I personally would expect)

- Syntax checking for errors
- Code completion
- Code reformatting
- Above features depend on version of Dockerfile and docker-compose.yml file (which are contained inside the file itself)

References:
https://docs.docker.com/engine/reference/builder/
https://docs.docker.com/compose/compose-file/

**Describe alternatives you've considered**
Alternative would be to not have these languages available. This would be possible, but editors commonly support them (idea suite, vscode etc. etc.)

Dockerfile & docker-compose.yml are dialects of Yaml so I would expect the solution to depend on yaml support.

**Screenshots**
-

**Comment by JosephTLyons** [comment]
I've moved this issue over to the extensions repository. I'm keeping it open, since Docker Compose files are not addressed via an extension yet.

**Comment by eth0net** [comment]
Working on adding the Docker Compose language server now 👀

**Comment by eth0net** [comment]
#578 adds support for the compose language server, just waiting for approval and merge 🚀

**Comment by JosephTLyons** [comment]
The extension store now supports both Docker and Docker Compose:

<img width="1478" alt="SCR-20240419-cmoq" src="https://github.com/zed-industries/extensions/assets/19867440/e266bbda-249f-480d-8c30-6c66cedee868">

**Comment by nohant** [comment]
great job @JosephTLyons !
Thanks a lot
