### ISSUE TITLE
Rewrap text

### ISSUE THREAD

**Issue by xpe** [zed-industries/extensions#515]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like "rewrap" functionality for Zed. Here is a VS Code plugin that does it: https://github.com/stkb/Rewrap -- with screenshots for those who aren't familiar.

Synonyms include:

- reflow text
- manual wrapping

## Related

- https://github.com/zed-industries/zed/issues/4588

**Comment by lylythechosenone** [comment]
Is anybody on this? It's an awesome feature that I miss greatly from VSCode—I daresay I could never go back.

**Comment by sunshowers** [comment]
> The Rewrap one is Alt-Q. But I have no idea why they chose Q, I wonder if the author of the plugin just wanted to find a corner key because it's convenient. If this is true, then I have a suspicion that this is a shortcut that can commonly conflict with other extensions' shortcuts.

M-Q (Alt-Q) is the Emacs shortcut for this feature: https://www.gnu.org/software/emacs/manual/html_node/emacs/Fill-Commands.html

**Comment by bartekpacia** [comment]
I'd really love to see this feature being built-in to Zed!

I totally agree with @szhu above – I can't imagine wrapping Markdown manually after I started using [Rewrap](https://github.com/stkb/Rewrap) (which seems to be, unfortunately, not maintained anymore).

**Comment by vincentisambart** [comment]
Seems to have been implemented in Zed's main branch, scheduled to be in stable next week:

- https://x.com/zeddotdev/status/1836468422017691853
- https://github.com/zed-industries/zed/pull/17909
- https://github.com/zed-industries/zed/pull/17953

**Comment by xpe** [comment]
Today I got Zed Preview 0.154.0 which has the 'rewrap' command. 🎸

**Comment by JosephTLyons** [comment]
Yep! This will be in stable next Wednesday, as a core editor command, so I'm going to close this issue out!

**Comment by mocenigo** [comment]
> Seems to have been implemented in Zed's main branch, scheduled to be in stable next week:
> 
> * https://x.com/zeddotdev/status/1836468422017691853
> * [editor: Add rewrap command zed#17909](https://github.com/zed-industries/zed/pull/17909)
> * [Bind `editor::Rewrap` to `alt-q` zed#17953](https://github.com/zed-industries/zed/pull/17953)

Maybe it is broken? I have a file with some long lines, and selecting the entire content and then picking editor::rewrap from the command palette... does nothing.

**Comment by istathar** [comment]
So `editor::Rewrap` _does_ work in a plain text file, but it's _not_ working in a Typst document (being the file format / extension in which I really wish wrapping would work right now). It's entirely possible that Zed is deferring to the extension which is in turn ... ignoring it?

What I'd really like would be to select a block of text characters and to have it rewrapped at 80 no matter what language or file format the editor thinks is present.

**Comment by xpe** [comment]
@istathar Do you know why? How do functions get delegated to different formats/document types? (I don't know BTW)

**Comment by istathar** [comment]
> Do you know why? How do functions get delegated to different formats/document types?

Yes, I figured out why it is happening: at first I thought it might be the language extension I was using but no, the code in Zed itself explicitly only runs if the file type is "Plain Text" or "Markdown" currently. I filed this bug about it:

- https://github.com/zed-industries/zed/issues/24242

**Comment by jaredallard** [comment]
Is the rewrap command meant to be ran manually? One of the things I liked about Rewrap in VSCode is that it ran automatically when going over a configured line length. Is that being tracked somewhere else / am I missing how to do that today?

**Comment by istathar** [comment]
@jaredallard fyi this was fixed this upstream in https://github.com/zed-industries/zed/pull/25173 there are some new configuration options available to control rewrapping behaviour.

**Comment by seba1342** [comment]
@istathar as far as I can tell the above is just for configuring rewrap per language. I think what @jaredallard was asking for was not having to run the the `editor:rewrap` command manually to trigger rewrap. But instead, being able to have it trigger as it reaches the max line length, or as a hook into the other document formatting. Is this something that is possible, or not yet?

**Comment by jaredallard** [comment]
@seba1342 is 100% right! This has been driving me crazy every time I try to switch to Zed. I really wish I could have this automatically run on `space`, basically!
