### ISSUE TITLE
EmmyLua

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/extensions#546]
### Check for existing issues

- [X] Completed

### Language

Lua

### Language server link

https://github.com/EmmyLua/EmmyLua-LanguageServer

### Misc notes

https://github.com/EmmyLua/IntelliJ-EmmyLua

**Comment by bananasov** [comment]
Any reason to use this over the [lua-language-server](https://github.com/LuaLS/lua-language-server)?

**Comment by 0x2CA** [comment]
There doesn't seem to be much of a difference.

**Comment by bananasov** [comment]
> There doesn't seem to be much of a difference.

The main difference is the way annotations are done, they are not cross compatible. the lua-language-server is also more used than EmmyLua

**Comment by 0x2CA** [comment]
My original purpose for opening this issues was just that the previous project was using EmmyLua and adding this might be good for older projects, but it's not that far off from  lua-language-server, and I see that  lua-language-server also references the EmmyLua implementation
