### ISSUE TITLE
No docs for creating language extensions

### ISSUE THREAD

**Issue by eth0net** [zed-industries/extensions#553]
Please can we get some documentation on the requirements for language files?

I was attempting to build [zed-vhs](https://github.com/eth0net/zed-vhs) with no prior knowledge on tree-sitter or the like and managed to only by trial and error.

In particular, please describe the `config.toml` format which I believe is unique to Zed Extensions. 

Documentation and examples on how to create the `.scm` files and mentions of them being `Scheme` files would also be useful. Especially details on supported/recommended highlight names and which `.scm` files are supported as I saw a diverse number while exploring other extensions.

**Comment by maxdeviant** [comment]
> In particular, please describe the `config.toml` format which I believe is unique to Zed Extensions.

The language `config.toml` is specified by this struct here: https://github.com/zed-industries/zed/blob/1127b1a0deb2821c4cc688417ccb9348da65ef48/crates/language/src/language.rs#L532-L604

Better docs will be coming in the future.

**Comment by eth0net** [comment]
I'll take a look over that, thanks for the info!
