### ISSUE TITLE
Could not enable extensions

### ISSUE THREAD

**Issue by emadbaqeri** [zed-industries/extensions#59]
Hey folks, I'm using Zed 0.122.2 but I couldn't enable extensions. I mean `zed: extensions` is not appearing on the command palette. There isn't any directory called _extensions_ in `~/Library/Application\ Support/Zed`. Is there any step that I'm missing?

**Comment by maxdeviant** [comment]
Extensions are currently only available in the Preview channel of Zed (Zed 0.123.2, at time of writing).

They will land on Stable this week (most likely on Wednesday).
