### ISSUE TITLE
Dart

### ISSUE THREAD

**Issue by WeetHet** [zed-industries/extensions#592]
### Check for existing issues

- [X] Completed

### Language

Dart

### Tree Sitter parser link

https://github.com/UserNobody14/tree-sitter-dart

### Language server link

https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec

**Comment by maxdeviant** [comment]
We have a Dart extension available here: https://github.com/zed-industries/zed/tree/a111b959d282d643d022b3c17b9f5ebba5aa8094/extensions/dart.

**Comment by WeetHet** [comment]
Oh yes, thanks, I've somehow missed it
