### ISSUE TITLE
[theme] Tomorrow night blue from VScode

### ISSUE THREAD

**Issue by williamdes** [zed-industries/extensions#593]
### Check for existing issues

- [X] Completed

### Misc notes

https://github.com/microsoft/vscode/tree/main/extensions/theme-tomorrow-night-blue

**Comment by williamdes** [comment]
https://github.com/chriskempson/tomorrow-theme

@chriskempson are you also the author for Vscode?

**Comment by d1y** [comment]
@williamdes 

Converting themes in vscode to zed is easy, theme_importer is built into the zed source code :)
FYI: https://github.com/d1y/vscode-monokaicharcoal.zed/blob/f46eb0c5b9ef9be0d1bd1f99b96d9b615949361d/gen.js#L15-L54

**Comment by williamdes** [comment]
Thank you @d1y for the importer link

Finally the way I found to work is:
https://github.com/zed-industries/zed/blob/main/crates/theme_importer/README.md?plain=1
https://zed.dev/blog/user-themes-now-in-preview

```sh
wget https://raw.githubusercontent.com/microsoft/vscode/main/extensions/theme-tomorrow-night-blue/themes/tomorrow-night-blue-color-theme.json
theme_importer ./tomorrow-night-blue-color-theme.json
ls ~/.config/zed/themes/
# Theme is here
```

**Comment by blaqat** [comment]
Currently working on porting [Tomorrow](https://github.com/biaqat/tomorrow-theme-zed.git) to Zed which will include this theme based off VSCode's Tomorrow Night Blue.
Should be making a PR soon.
<img src="https://github.com/bIaqat/tomorrow-theme-zed/raw/main/assets/tomorrow-night-blue.png" />

**Comment by chriskempson** [comment]
> https://github.com/chriskempson/tomorrow-theme
> 
> @chriskempson are you also the author for VS Code?

That theme has been around in VS Code since forever. I'm not sure but I have a Microsoft used my TextMate theme and imported it somehow.
