### ISSUE TITLE
Meson

### ISSUE THREAD

**Issue by WeetHet** [zed-industries/extensions#595]
### Check for existing issues

- [X] Completed

### Language

Meson

### Tree Sitter parser link

https://github.com/tree-sitter-grammars/tree-sitter-meson

### Language server link

https://github.com/JCWasmx86/mesonlsp

### Misc notes

Tree sitter grammar is enough for basically everything, lsp is not really required

**Comment by hqnna** [comment]
Started working on this myself, syntax highlighting works, need to do the LSP stuff then it'd be finished.
https://github.com/hqnna/zed-meson

**Comment by WeetHet** [comment]
Great thanks!
