### ISSUE TITLE
Sublime Text 4 theme

### ISSUE THREAD

**Issue by jackTabsCode** [zed-industries/extensions#642]
### Check for existing issues

- [X] Completed

**Comment by JosephTLyons** [comment]
Hey @jackTabsCode, can you specify which specific themes you are looking for? Thanks.

**Comment by jackTabsCode** [comment]
> Hey @jackTabsCode, can you specify which specific themes you are looking for? Thanks.

I'm looking for the default light and dark themes @JosephTLyons 

![image](https://github.com/user-attachments/assets/ca509e0e-81a9-4810-bf7c-648d0b838f2d)

**Comment by blaqat** [comment]
I actually have been working on [this theme](https://github.com/biaqat/mariana-theme-zed.git) based off of Sublime 3.
Should be making a PR soon.

<p float="left">
  <img src="https://github.com/bIaqat/mariana-theme-zed/raw/main/assets/mariana.png" width="45%" />
  <img src="https://github.com/bIaqat/mariana-theme-zed/raw/main/assets/mariana-breakers.png" width="45%" />
</p>
