### ISSUE TITLE
Aquarium

### ISSUE THREAD

**Issue by KeoFoxy** [zed-industries/extensions#646]
### Check for existing issues

- [X] Completed

### Misc notes

[Repo](https://github.com/FrenzyExists/aquarium-vim)

Preview

<img src="https://github.com/FrenzyExists/aquarium-vim/blob/develop/screenshots/pika_vim-dark.png?raw=true" />
<img src="https://nvchad.com/themes/aquarium.webp" />

**Comment by blaqat** [comment]
[Work in progress port](https://github.com/bIaqat/aquarium-theme-zed/tree/main)... 
Also can make a variant closer to your second screenshot highlights like the second image if you'd like
<table>
<tr>
    <td><img src="https://github.com/user-attachments/assets/7b8acecb-6392-4eee-baea-69ae5a4b7be3" width="700"></td>
    <td><img src="https://github.com/user-attachments/assets/f71018f0-aefd-4d4d-9bdf-43c0ad88dac9" width="700"></td>
  </tr>
 </table>

**Comment by KeoFoxy** [comment]
Thats great
Awesome!
Thanks a lot

**Comment by blaqat** [comment]
This theme extension has been merged, can be closed if everything looks alright!
