### ISSUE TITLE
Green Monochrome Monitor Theme

### ISSUE THREAD

**Issue by Takk8IS** [zed-industries/extensions#751]
### Check for existing issues

- [X] Completed

### Misc notes

# Green Monochrome Monitor Theme for Zed

The "Green Monochrome Monitor Theme" brings the nostalgic essence of vintage green phosphor monitors to your Zed editor. This theme is crafted to offer a unique and immersive visual experience, capturing the original charm of early computing displays. Available in both dark and light versions, the Green Monochrome Monitor Theme transforms your coding environment with its distinct green-on-black and green-on-light-green aesthetics.

https://github.com/Takk8IS/green-monochrome-monitor-theme-for-zed

## Green Monochrome Monitor Dark Theme
![screenshot-dark](https://github.com/zed-industries/zed/assets/152639968/fc8aecda-380a-4a27-8318-79c653304ad1)

## Green Monochrome Monitor Light Theme
![screenshot-light](https://github.com/zed-industries/zed/assets/152639968/bf375857-4f65-4834-ae67-8f62ad479a42)

## Theme Overview

The "Green Monochrome Monitor Theme" is designed to evoke the look and feel of classic CRT monitors, emphasizing simplicity and readability. The dark version features a predominantly black background with vibrant green text and accents, while the light version introduces a softer green background for a refreshing contrast. Both versions maintain a consistent color scheme that is easy on the eyes and suitable for long coding sessions.

## Installation Instructions

**1. Manual Install**

-   **Download**: Download the theme files (`green-monochrome-monitor-theme.json`) from the repository.
-   **Add**: Move the downloaded JSON file to the `~/.config/zed/themes/` directory on your macOS.
-   **Activate**: Open the Command Palette in Zed by typing `theme selector: toggle`, then search for "Green Monochrome Monitor Theme" to apply the theme.

**2. Install via Command Palette**

-   **Open**: Open the Command Palette in Zed by navigating to the menu and selecting `Go > Open Command Palette...`.
-   **Type**: Type `extensions` or `zed: extensions` in the Command Palette.
-   **Search**: Search for "Green Monochrome Monitor Theme" and install it directly from the extension marketplace.

**3. Activate**

-   **Open**: Open the Command Palette in Zed by navigating to the menu and selecting `Go > Open Command Palette...`.
-   **Type**: Type `theme selector: toggle`.
-   **Search**: Search for "Green Monochrome Monitor Theme" and select it from the list to activate the theme.

Enjoy coding with the nostalgic and visually soothing aesthetics of the Green Monochrome Monitor Theme. Whether you prefer the dark version's striking green-on-black contrast or the light version's refreshing green tones, this theme will enhance your Zed editor experience with a touch of vintage charm.

## Theme Details

**Green Monochrome Monitor Dark Theme**

-   **Background**: #000000
-   **Foreground**: #0BD904
-   **Accent Colors**: Various shades of green for borders, highlights, and syntax elements.
-   **Syntax Highlighting**: Strong emphasis on readability with bold green text for keywords, strings, and other elements.

**Green Monochrome Monitor Light Theme**

-   **Background**: #000000
-   **Foreground**: #00FF00
-   **Accent Colors**: Light green tones for borders, highlights, and syntax elements.
-   **Syntax Highlighting**: Enhanced visibility with lighter green text for keywords, strings, and other elements.

Both versions of the theme ensure a cohesive and immersive experience, making your coding environment visually appealing and reminiscent of classic green phosphor monitors.

Experience the originality and unique aesthetics of the Green Monochrome Monitor Theme and take your coding journey back to the era of early computing displays.

### Support

Experience the power of ZED by visiting their official website today at https://zed.dev/.

**Comment by JosephTLyons** [comment]
Hey @Takk8IS, are you wanting to upload this theme to our extensions store? The issues here are usually reserved for users who are looking to get a theme or language package made up, but it seems you've already made this extensions - do you want to publish it?

**Comment by Takk8IS** [comment]
Hello, my dear Sim. My intention is precisely to contribute to the ZED community. Always thinking of the best possible quality, both for the designer, front-end, back-end, and Tech Leads. Besides that, I also have some other resources that I want to add as an extension. But this message I usually published... It is the theme in ZED Theme Extensions store.
Can you help me, please?

**Comment by Takk8IS** [comment]
Hi @JosephTLyons https://github.com/Takk8IS/green-monochrome-monitor-theme-for-zed Updated with new colours =)

**Comment by maxdeviant** [comment]
Done in https://github.com/zed-industries/extensions/pull/816.
