### ISSUE TITLE
Syntax recognition ruby

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/extensions#803]
### Check for existing issues

- [X] Completed

### Misc notes

Vscode:
<img width="927" alt="Screenshot 2024-05-28 alle 20 38 47" src="https://github.com/zed-industries/extensions/assets/20476002/34df5f0e-0be1-4079-94bd-98903ff34076">
Zed:
<img width="927" alt="Screenshot 2024-05-28 alle 20 38 57" src="https://github.com/zed-industries/extensions/assets/20476002/3d269a06-2220-49ba-bc88-c65985b46292">

**Comment by Moshyfawn** [comment]
You should already be able to install [the Ruby language extension](https://github.com/zed-industries/zed/tree/main/extensions/ruby) from the Extensions tab in Zed.

**Comment by janko** [comment]
`Podfile` probably just needs to be added to [this list](https://github.com/zed-industries/zed/blob/da70741ece40732e9a4c720159c839a0c14694d6/extensions/ruby/languages/ruby/config.toml#L3-L23).

**Comment by Moshyfawn** [comment]
> `Podfile` probably just needs to be added to [this list](https://github.com/zed-industries/zed/blob/da70741ece40732e9a4c720159c839a0c14694d6/extensions/ruby/languages/ruby/config.toml#L3-L23).

Yup, exactly. Just created the PR.

**Comment by Moshyfawn** [comment]
> @Moshyfawn :  You can add this extension too: `podspec`

Feel free to open a PR with the proposed change 😉
