### ISSUE TITLE
Add HTTP Support

### ISSUE THREAD

**Issue by kyocodary** [zed-industries/extensions#853]
### Check for existing issues

- [X] Completed

### Language

HTTP

### Misc notes

Like the [Rest Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) extension of vscode, it will be possible to define multiple http requests by defining them within the .http file and view the response directly.

Example:
![image](https://github.com/zed-industries/extensions/assets/1796545/8ca87199-78ea-41ee-a4cb-8e80fb093cc6)

**Comment by andremacola** [comment]
Oh my god, this will be super!!

I recommend HTTPYac Cli: https://httpyac.github.io/guide/installation_cli.html
There is a VSCode extension https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac

HTTPYac is way better than RestClient

**Comment by JosephTLyons** [comment]
Looks like we have an extension now, so I'm closing this out!

<img width="712" alt="SCR-20241110-brjd" src="https://github.com/user-attachments/assets/0a09aa2f-93db-4616-87a8-36fce83012dc">

**Comment by fabioalmeidaweb** [comment]
@JosephTLyons , unfortunately, this extension only provides syntax highlights. It doesn't provide a way to make requests like the REST Client.
Couldn't we open it again?

**Comment by nDmitry** [comment]
The only thing I still open VS Code is its Rest Client extension. Good to have HTTP syntax highlighting now, but really miss inline HTTP requests execution in Zed.

**Comment by MoskitoHero** [comment]
Just added a PR to the http extension adding tasks, in case anyone is interested: https://github.com/tie304/zed-http/pull/5

**Comment by fabioalmeidaweb** [comment]
> Just added a PR to the http extension adding tasks, in case anyone is interested: [tie304/zed-http#5](https://github.com/tie304/zed-http/pull/5)

Amazing, wanna try soon! haha

**Comment by michalss** [comment]
> Just added a PR to the http extension adding tasks, in case anyone is interested: [tie304/zed-http#5](https://github.com/tie304/zed-http/pull/5)

yeah nice this is very needed :)

**Comment by miklereverie** [comment]
+1 to this! The only reason I open VSCode nowadays is to use the rest client extension

**Comment by Onyelaudochukwuka** [comment]
+1, I literally have to switch back to WebStorm just to make simple HTTP requests. Can we move this forward a bit faster? This is blocking my workflow.

**Comment by michalss** [comment]
Is there any progress? This is the last thing i cannot complitely switch to zed :(
