### ISSUE TITLE
Panda

### ISSUE THREAD

**Issue by scbizu** [zed-industries/extensions#87]
### Check for existing issues

- [X] Completed

### Misc notes

Panda Syntax Theme : https://github.com/tinkertrain/panda-syntax-vscode

**Comment by blaqat** [comment]
The dark variant in [my wip panda port](https://github.com/biaqat/panda-theme-zed.git) is based off panda syntax from vscode as well as [moe panda](https://marketplace.visualstudio.com/items?itemName=moetype.moe-panda-theme).
Should be opening a PR soon.

<img src="https://github.com/bIaqat/panda-theme-zed/raw/main/assets/panda.png" />
