### ISSUE TITLE
List of extensions not currently supported

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/extensions#883]
### Check for existing issues

- [X] Completed

### Describe the feature

- [ ] babelrc (JSON)
- [ ] clang-format (YAML)
- [ ] code-workspace (JSON)
- [ ] eslintrc (JSON)
- [ ] m (c,cpp)
- [ ] mm (c,cpp)
- [ ] metal (c,cpp)
- [ ] prettierrc (JSON)
- [ ] resolved (JSON)
- [ ] xctestplan (JSON)
- [ ] xcstrings (JSON)

In brackets the language it is closest to in terms of syntax recognition.

**Comment by maxdeviant** [comment]
I appreciate the effort in compiling this, but I think this list is too likely to get outdated over time.
