### ISSUE TITLE
Under Extensions create separate folders for theme, syntax support and more

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/extensions#911]
### Check for existing issues

- [X] Completed

**Comment by Moshyfawn** [comment]
Does zed-industries/zed#8848 seem close to what you're after?

**Comment by someone13574** [comment]
Can't extensions have both language support and a theme in one? Not sure if there any any atm, but it's possible I believe.

**Comment by maxdeviant** [comment]
We don't be doing this.

The organization of this repository is intentional, and fine as it is.
