### ISSUE TITLE
Submodules non-existent

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/extensions#924]
### Check for existing issues

- [X] Completed

### Misc notes

Repository that doesn't exist on github:

<img width="1306" alt="Screenshot 2024-06-11 alle 21 02 48" src="https://github.com/zed-industries/extensions/assets/20476002/6fa03deb-2422-424b-8ad6-4449bee49687">

![image](https://github.com/zed-industries/extensions/assets/20476002/ad6e798e-6a64-4d61-9abb-4e29e5f5db7c)

Repository that does not exist on github, but on gitlab:

<img width="1331" alt="Screenshot 2024-06-11 alle 21 03 00" src="https://github.com/zed-industries/extensions/assets/20476002/f2c63e0d-c3e2-4448-8191-0c88d97283e5">

![image](https://github.com/zed-industries/extensions/assets/20476002/837783dd-6e08-457c-9307-7be0d4b0baef)

Submodules zed that shouldn't be there:
<img width="1321" alt="Screenshot 2024-06-11 alle 21 04 30" src="https://github.com/zed-industries/extensions/assets/20476002/123b427a-0aaa-4b21-af07-591f33b15e95">

**Comment by maxdeviant** [comment]
> ### Check for existing issues
> * [x]  Completed
> 
> ### Misc notes
> Repository that doesn't exist on github:
> 
> <img alt="Screenshot 2024-06-11 alle 21 02 48" width="1306" src="https://private-user-images.githubusercontent.com/20476002/338714415-6fa03deb-2422-424b-8ad6-4449bee49687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzYyNDAsIm5iZiI6MTcxODEzNTk0MCwicGF0aCI6Ii8yMDQ3NjAwMi8zMzg3MTQ0MTUtNmZhMDNkZWItMjQyMi00MjRiLThhZDYtNDQ0OWJlZTQ5Njg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE5NTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNDRlZjZmYmQ3ZGM2OGYwNDI5YzFhZTBjZTNmOWVjODIzNDcxZmE2ZDYwZDMzYzk2ZTY4NDNhNGJiOGNlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNte21ztGR49r3gblo_lbE-nolqhLK-BP5TebTgRfhk">

This appears to be a problem with the extension's metadata:

https://gitlab.com/Fake.User/struct-zed-theme/-/blob/main/extension.toml?ref_type=heads#L7

The URL to the extension repository is correct in this repository: https://github.com/zed-industries/extensions/blob/0e061e18d42f19eded79addf043e9c45f6ad13d9/.gitmodules#L595

This would need to be addressed by the extension author.

> ![image](https://private-user-images.githubusercontent.com/20476002/338714510-ad6e798e-6a64-4d61-9abb-4e29e5f5db7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzYyNDAsIm5iZiI6MTcxODEzNTk0MCwicGF0aCI6Ii8yMDQ3NjAwMi8zMzg3MTQ1MTAtYWQ2ZTc5OGUtNmE2NC00ZDYxLTlhYmItNGUyOWU1ZjVkYjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE5NTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmOGQ0MjkzMjY2N2E4ZDhmNzhhOGY2Y2VmZjVkMTE3YWRlMmRjOWYxMzc2OTc5ZTQ3ZjI5MTE1M2M4MGY2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rz4TW46yftMiuQq2JOo7WGNe9LLkj9JME5Cqf8xQvkA)
> 
> Repository that does not exist on github, but on gitlab:
> 
> <img alt="Screenshot 2024-06-11 alle 21 03 00" width="1331" src="https://private-user-images.githubusercontent.com/20476002/338714423-f2c63e0d-c3e2-4448-8191-0c88d97283e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzYyNDAsIm5iZiI6MTcxODEzNTk0MCwicGF0aCI6Ii8yMDQ3NjAwMi8zMzg3MTQ0MjMtZjJjNjNlMGQtYzNlMi00NDQ4LTgxOTEtMGM4OGQ5NzI4M2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE5NTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YTVkMjJiOTUwMmRmYjZiYzM4OWFlYWQxYjExOGY3MjFkNWVjODZhNDk5MmZjNDAwYzhjNmMyMTFjNTQ1N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XmM9bvdxzLe3H5RXQKdQAGleaVXuwRwcgmLY2vKcWqc">
> ![image](https://private-user-images.githubusercontent.com/20476002/338714558-837783dd-6e08-457c-9307-7be0d4b0baef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzYyNDAsIm5iZiI6MTcxODEzNTk0MCwicGF0aCI6Ii8yMDQ3NjAwMi8zMzg3MTQ1NTgtODM3NzgzZGQtNmUwOC00NTdjLTkzMDctN2JlMGQ0YjBiYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE5NTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMGQ1NmNiYWMyZDAyMDUyNGExMWZlODU2YWMwYzIwYWRkNjE1NjNhYjdhNWJkMGNkMDZkYmFhYWY1YzE1YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MhWea64mTT11a2T_7C5lxVmWu7V4zuIfZVZQ-BMPgzo)

We don't require that extensions live on GitHub, so it's fine that it is on GitLab.

It would be nice if the GitHub UI supported this better, but that is a GitHub problem, not a Zed problem.

> Submodules zed that shouldn't be there: <img alt="Screenshot 2024-06-11 alle 21 04 30" width="1321" src="https://private-user-images.githubusercontent.com/20476002/338714428-123b427a-0aaa-4b21-af07-591f33b15e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzYyNDAsIm5iZiI6MTcxODEzNTk0MCwicGF0aCI6Ii8yMDQ3NjAwMi8zMzg3MTQ0MjgtMTIzYjQyN2EtMGFhYS00YjIxLWFmMDctNTkxZjMzYjE1ZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE5NTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYzA5Y2E5YjJlMjZkN2MyZjZiNTNhNmZkODE2NmNjMTQ0ODc1OGExNTQxNDI3ZmQyNGIwMTFlZTg2MTE1MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nwEjOL3lPeI4_eV9drWzLD_nhGopaYQWhTyaf-w18ik">

This is intentional.

We use it to reference the extensions that reside in the Zed repo.
