### ISSUE TITLE
Dark Modern (VS Code Theme)

### ISSUE THREAD

**Issue by GXM245** [zed-industries/extensions#933]
### Check for existing issues

- [X] Completed

### Misc notes

Has anyone been able to port over the Dark Modern VS Code theme?
I've tried using the Theme -> Zed extension with no luck, and the cargo solution on Zed's website doesn't seem to work for me. 

Can anyone who has had luck with this before please post a port? 🙏 Thank you!!!

**Comment by Moshyfawn** [comment]
Yup, search for `dark modern`.

<img width="1396" alt="image" src="https://github.com/zed-industries/extensions/assets/16290753/46572faa-3e62-4d99-8eb9-849fe850d8a7">

**Comment by GXM245** [comment]
@Moshyfawn - Yes you're right, I did actually try this theme, but unfortunately, it's not a close replica of the original theme. Please see example image below:

Apologies I wasn't as specific as I should have been. Would appreciate if you could re-open the issue.

Do you, by any chance, have just a default port of the theme you might be able to provide with no additional edits or personalisations?

Many thanks!

<img width="1500" alt="image" src="https://github.com/zed-industries/extensions/assets/69755684/f811607d-36ba-4561-8d31-b66571f3bf0f">
