### ISSUE TITLE
SynthWave '84

### ISSUE THREAD

**Issue by vinayakkulkarni** [zed-industries/extensions#95]
### Check for existing issues

- [X] Completed

### Misc notes

If possible, would love if SynthWave '84 theme could be integrated in Zed. This and Tailwind css within Vue (ref: https://github.com/zed-industries/zed/issues/4403#issuecomment-1908619775) would be the final nail in the coffin for VS Code for me.

SynthWave '84 :- https://github.com/robb0wen/synthwave-vscode

Thank you. Appreciate all the hard work put by the team & community.

**Comment by maxdeviant** [comment]
Looks like #50 might satisfy this.

**Comment by vinayakkulkarni** [comment]
> Looks like #50 might satisfy this.

It seems it’s partially done. The most important part of SythWave is the neon dreams which isn’t implemented

**Comment by maxdeviant** [comment]
> > Looks like #50 might satisfy this.
> 
> It seems it’s partially done. The most important part of SythWave is the neon dreams which isn’t implemented

That part isn't able to be implemented in our current theme system, unfortunately.

**Comment by ifsheldon** [comment]
+1. Neon Dreams hacks vscode, but it'd be great if Zed can have an API to control lighting of characters in some way.

**Comment by JosephTLyons** [comment]
A [Synthwave '84 Theme extension](https://github.com/DanielMSchmidt/zed-synthwave) now exists.

<img width="715" alt="SCR-20240716-mncf" src="https://github.com/user-attachments/assets/2192557d-0ecf-485e-8c88-1b93bdf2b52b">

**Comment by ifsheldon** [comment]
Glow/Neon Dreams is not supported yet according to https://github.com/DanielMSchmidt/zed-synthwave/issues/2 . So I don't think it's completed yet.
