### ISSUE TITLE
The D extension is difficult to install

### ISSUE THREAD

**Issue by pdenapo** [zed-industries/extensions#961]
### Check for existing issues

- [X] Completed

### Language

D

### Tree Sitter parser link

https://github.com/gdamore/tree-sitter-d

### Language server link

https://github.com/Pure-D/serve-d

### Misc notes

There seems to be a wok-in progress D extension for zed 

https://github.com/staysail/zed-d/

However, it does not seem to be a very active
project and it is not easy to install (Zed does not recognize the D files and does not offer to install any extension). See my report at

https://github.com/staysail/zed-d/issues/5

(There was no answer from the author).

**Comment by maxdeviant** [comment]
I left a comment on the issue you opened on the other repo: https://github.com/staysail/zed-d/issues/5#issuecomment-2189074216

The D extension can be installed from the extension registry, same as other extensions, so I don't think there is anything that needs to be done here.
